// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_64_64_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        p_ZL4demo_0_1_address0,
        p_ZL4demo_0_1_ce0,
        p_ZL4demo_0_1_q0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_q0,
        p_ZL4demo_1_1_address0,
        p_ZL4demo_1_1_ce0,
        p_ZL4demo_1_1_q0,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_q0,
        p_ZL4demo_2_1_address0,
        p_ZL4demo_2_1_ce0,
        p_ZL4demo_2_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [13:0] p_ZL4demo_0_1_address0;
output   p_ZL4demo_0_1_ce0;
input  [7:0] p_ZL4demo_0_1_q0;
output  [13:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
input  [7:0] p_ZL4demo_1_0_q0;
output  [13:0] p_ZL4demo_1_1_address0;
output   p_ZL4demo_1_1_ce0;
input  [7:0] p_ZL4demo_1_1_q0;
output  [13:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
input  [7:0] p_ZL4demo_1_2_q0;
output  [13:0] p_ZL4demo_2_1_address0;
output   p_ZL4demo_2_1_ce0;
input  [7:0] p_ZL4demo_2_1_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln143_fu_162_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] i_11_load_reg_324;
reg   [5:0] i_11_load_reg_324_pp0_iter1_reg;
wire   [0:0] icmp_ln145_fu_180_p2;
reg   [0:0] icmp_ln145_reg_329;
reg   [0:0] icmp_ln145_reg_329_pp0_iter1_reg;
wire   [5:0] indvars_iv_next3029_fu_194_p2;
reg   [5:0] indvars_iv_next3029_reg_334;
reg   [5:0] indvars_iv_next3029_reg_334_pp0_iter1_reg;
wire   [5:0] add_ln147_fu_227_p2;
reg   [5:0] add_ln147_reg_364;
reg   [5:0] add_ln147_reg_364_pp0_iter1_reg;
reg   [7:0] par2_reg_369;
reg   [7:0] par1_reg_374;
wire   [7:0] add_ln15_2_fu_260_p2;
reg   [7:0] add_ln15_2_reg_379;
wire   [63:0] zext_ln12_fu_218_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln147_fu_284_p1;
reg   [5:0] j_fu_54;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_load;
reg   [5:0] i_11_fu_58;
wire   [5:0] select_ln143_3_fu_200_p3;
reg   [5:0] ap_sig_allocacmp_i_11_load;
reg   [11:0] indvar_flatten42_fu_62;
wire   [11:0] add_ln143_fu_168_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten42_load;
reg    p_ZL4demo_0_1_ce0_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_1_1_ce0_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    p_ZL4demo_2_1_ce0_local;
reg    out_r_we0_local;
wire   [7:0] add_ln15_3_fu_293_p2;
reg    out_r_ce0_local;
wire   [5:0] select_ln143_fu_186_p3;
wire   [12:0] tmp_s_fu_208_p4;
wire   [7:0] shl_ln15_fu_248_p2;
wire   [7:0] sub_ln15_fu_254_p2;
wire   [5:0] indvars_iv_next30_mid1_fu_266_p2;
wire   [5:0] select_ln143_4_fu_271_p3;
wire   [11:0] tmp_9_fu_277_p3;
wire   [7:0] add_ln15_fu_289_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_54 = 6'd0;
#0 i_11_fu_58 = 6'd0;
#0 indvar_flatten42_fu_62 = 12'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_162_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_11_fu_58 <= select_ln143_3_fu_200_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_11_fu_58 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_162_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten42_fu_62 <= add_ln143_fu_168_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten42_fu_62 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_162_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_54 <= add_ln147_fu_227_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_54 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln147_reg_364 <= add_ln147_fu_227_p2;
        add_ln147_reg_364_pp0_iter1_reg <= add_ln147_reg_364;
        add_ln15_2_reg_379 <= add_ln15_2_fu_260_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_11_load_reg_324 <= ap_sig_allocacmp_i_11_load;
        i_11_load_reg_324_pp0_iter1_reg <= i_11_load_reg_324;
        icmp_ln145_reg_329 <= icmp_ln145_fu_180_p2;
        icmp_ln145_reg_329_pp0_iter1_reg <= icmp_ln145_reg_329;
        indvars_iv_next3029_reg_334 <= indvars_iv_next3029_fu_194_p2;
        indvars_iv_next3029_reg_334_pp0_iter1_reg <= indvars_iv_next3029_reg_334;
        par1_reg_374 <= p_ZL4demo_1_0_q0;
        par2_reg_369 <= p_ZL4demo_0_1_q0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_162_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_11_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_11_load = i_11_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten42_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten42_load = indvar_flatten42_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 6'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln143_fu_168_p2 = (ap_sig_allocacmp_indvar_flatten42_load + 12'd1);

assign add_ln147_fu_227_p2 = (select_ln143_fu_186_p3 + 6'd1);

assign add_ln15_2_fu_260_p2 = (sub_ln15_fu_254_p2 + p_ZL4demo_1_2_q0);

assign add_ln15_3_fu_293_p2 = (add_ln15_2_reg_379 + add_ln15_fu_289_p2);

assign add_ln15_fu_289_p2 = (par1_reg_374 + par2_reg_369);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln143_fu_162_p2 = ((ap_sig_allocacmp_indvar_flatten42_load == 12'd3844) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_180_p2 = ((ap_sig_allocacmp_j_load == 6'd62) ? 1'b1 : 1'b0);

assign indvars_iv_next3029_fu_194_p2 = (ap_sig_allocacmp_i_11_load + 6'd1);

assign indvars_iv_next30_mid1_fu_266_p2 = (i_11_load_reg_324_pp0_iter1_reg + 6'd2);

assign out_r_address0 = zext_ln147_fu_284_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = add_ln15_3_fu_293_p2;

assign out_r_we0 = out_r_we0_local;

assign p_ZL4demo_0_1_address0 = zext_ln12_fu_218_p1;

assign p_ZL4demo_0_1_ce0 = p_ZL4demo_0_1_ce0_local;

assign p_ZL4demo_1_0_address0 = zext_ln12_fu_218_p1;

assign p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;

assign p_ZL4demo_1_1_address0 = zext_ln12_fu_218_p1;

assign p_ZL4demo_1_1_ce0 = p_ZL4demo_1_1_ce0_local;

assign p_ZL4demo_1_2_address0 = zext_ln12_fu_218_p1;

assign p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;

assign p_ZL4demo_2_1_address0 = zext_ln12_fu_218_p1;

assign p_ZL4demo_2_1_ce0 = p_ZL4demo_2_1_ce0_local;

assign select_ln143_3_fu_200_p3 = ((icmp_ln145_fu_180_p2[0:0] == 1'b1) ? indvars_iv_next3029_fu_194_p2 : ap_sig_allocacmp_i_11_load);

assign select_ln143_4_fu_271_p3 = ((icmp_ln145_reg_329_pp0_iter1_reg[0:0] == 1'b1) ? indvars_iv_next30_mid1_fu_266_p2 : indvars_iv_next3029_reg_334_pp0_iter1_reg);

assign select_ln143_fu_186_p3 = ((icmp_ln145_fu_180_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_j_load);

assign shl_ln15_fu_248_p2 = p_ZL4demo_1_1_q0 << 8'd2;

assign sub_ln15_fu_254_p2 = (p_ZL4demo_2_1_q0 - shl_ln15_fu_248_p2);

assign tmp_9_fu_277_p3 = {{select_ln143_4_fu_271_p3}, {add_ln147_reg_364_pp0_iter1_reg}};

assign tmp_s_fu_208_p4 = {{{select_ln143_3_fu_200_p3}, {1'd0}}, {select_ln143_fu_186_p3}};

assign zext_ln12_fu_218_p1 = tmp_s_fu_208_p4;

assign zext_ln147_fu_284_p1 = tmp_9_fu_277_p3;

endmodule //real_top_img_sharp_64_64_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6
