// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_32_32_Pipeline_VITIS_LOOP_159_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        p_ZL4demo_0_0_address0,
        p_ZL4demo_0_0_ce0,
        p_ZL4demo_0_0_q0,
        p_ZL4demo_0_1_address0,
        p_ZL4demo_0_1_ce0,
        p_ZL4demo_0_1_q0,
        p_ZL4demo_0_2_address0,
        p_ZL4demo_0_2_ce0,
        p_ZL4demo_0_2_q0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_q0,
        p_ZL4demo_1_1_address0,
        p_ZL4demo_1_1_ce0,
        p_ZL4demo_1_1_q0,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [13:0] p_ZL4demo_0_0_address0;
output   p_ZL4demo_0_0_ce0;
input  [7:0] p_ZL4demo_0_0_q0;
output  [13:0] p_ZL4demo_0_1_address0;
output   p_ZL4demo_0_1_ce0;
input  [7:0] p_ZL4demo_0_1_q0;
output  [13:0] p_ZL4demo_0_2_address0;
output   p_ZL4demo_0_2_ce0;
input  [7:0] p_ZL4demo_0_2_q0;
output  [13:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
input  [7:0] p_ZL4demo_1_0_q0;
output  [13:0] p_ZL4demo_1_1_address0;
output   p_ZL4demo_1_1_ce0;
input  [7:0] p_ZL4demo_1_1_q0;
output  [13:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
input  [7:0] p_ZL4demo_1_2_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln159_fu_149_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] add_ln160_fu_155_p2;
reg   [4:0] add_ln160_reg_241;
reg   [4:0] add_ln160_reg_241_pp0_iter1_reg;
reg   [4:0] add_ln160_reg_241_pp0_iter2_reg;
wire   [63:0] zext_ln159_fu_161_p1;
reg   [63:0] zext_ln159_reg_246;
wire   [6:0] tmp117_fu_191_p2;
reg   [6:0] tmp117_reg_283;
reg   [7:0] p_ZL4demo_1_0_load_reg_288;
reg   [7:0] p_ZL4demo_1_2_load_reg_293;
wire   [7:0] add_ln53_2_fu_210_p2;
reg   [7:0] add_ln53_2_reg_298;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_fu_216_p1;
reg   [4:0] j_fu_46;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_6;
reg    p_ZL4demo_0_0_ce0_local;
reg    p_ZL4demo_0_2_ce0_local;
reg    p_ZL4demo_1_1_ce0_local;
reg    p_ZL4demo_0_1_ce0_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    out_r_we0_local;
wire   [7:0] add_ln53_3_fu_224_p2;
reg    out_r_ce0_local;
wire   [6:0] empty_fu_173_p1;
wire   [6:0] empty_38_fu_181_p1;
wire   [6:0] tmp17_fu_185_p2;
wire   [6:0] empty_37_fu_177_p1;
wire   [7:0] shl_ln53_fu_197_p2;
wire   [7:0] tmp_fu_203_p3;
wire   [7:0] add_ln53_fu_220_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_46 = 5'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln159_fu_149_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_46 <= add_ln160_fu_155_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln160_reg_241 <= add_ln160_fu_155_p2;
        add_ln160_reg_241_pp0_iter1_reg <= add_ln160_reg_241;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp117_reg_283 <= tmp117_fu_191_p2;
        zext_ln159_reg_246[4 : 0] <= zext_ln159_fu_161_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln160_reg_241_pp0_iter2_reg <= add_ln160_reg_241_pp0_iter1_reg;
        add_ln53_2_reg_298 <= add_ln53_2_fu_210_p2;
        p_ZL4demo_1_0_load_reg_288 <= p_ZL4demo_1_0_q0;
        p_ZL4demo_1_2_load_reg_293 <= p_ZL4demo_1_2_q0;
    end
end

always @ (*) begin
    if (((icmp_ln159_fu_149_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_6 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_6 = j_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_155_p2 = (ap_sig_allocacmp_j_6 + 5'd1);

assign add_ln53_2_fu_210_p2 = (shl_ln53_fu_197_p2 + tmp_fu_203_p3);

assign add_ln53_3_fu_224_p2 = (add_ln53_2_reg_298 + add_ln53_fu_220_p2);

assign add_ln53_fu_220_p2 = (p_ZL4demo_1_0_load_reg_288 + p_ZL4demo_1_2_load_reg_293);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_37_fu_177_p1 = p_ZL4demo_0_2_q0[6:0];

assign empty_38_fu_181_p1 = p_ZL4demo_1_1_q0[6:0];

assign empty_fu_173_p1 = p_ZL4demo_0_0_q0[6:0];

assign icmp_ln159_fu_149_p2 = ((ap_sig_allocacmp_j_6 == 5'd30) ? 1'b1 : 1'b0);

assign out_r_address0 = zext_ln160_fu_216_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = add_ln53_3_fu_224_p2;

assign out_r_we0 = out_r_we0_local;

assign p_ZL4demo_0_0_address0 = zext_ln159_fu_161_p1;

assign p_ZL4demo_0_0_ce0 = p_ZL4demo_0_0_ce0_local;

assign p_ZL4demo_0_1_address0 = zext_ln159_reg_246;

assign p_ZL4demo_0_1_ce0 = p_ZL4demo_0_1_ce0_local;

assign p_ZL4demo_0_2_address0 = zext_ln159_fu_161_p1;

assign p_ZL4demo_0_2_ce0 = p_ZL4demo_0_2_ce0_local;

assign p_ZL4demo_1_0_address0 = zext_ln159_reg_246;

assign p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;

assign p_ZL4demo_1_1_address0 = zext_ln159_fu_161_p1;

assign p_ZL4demo_1_1_ce0 = p_ZL4demo_1_1_ce0_local;

assign p_ZL4demo_1_2_address0 = zext_ln159_reg_246;

assign p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;

assign shl_ln53_fu_197_p2 = p_ZL4demo_0_1_q0 << 8'd2;

assign tmp117_fu_191_p2 = (tmp17_fu_185_p2 + empty_37_fu_177_p1);

assign tmp17_fu_185_p2 = (empty_fu_173_p1 + empty_38_fu_181_p1);

assign tmp_fu_203_p3 = {{tmp117_reg_283}, {1'd0}};

assign zext_ln159_fu_161_p1 = ap_sig_allocacmp_j_6;

assign zext_ln160_fu_216_p1 = add_ln160_reg_241_pp0_iter2_reg;

always @ (posedge ap_clk) begin
    zext_ln159_reg_246[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //real_top_img_sharp_32_32_Pipeline_VITIS_LOOP_159_9
