// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_128_128_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        p_read1,
        p_read2,
        p_read3,
        p_read5,
        p_read6,
        p_read7,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        out_r_address1,
        out_r_ce1,
        out_r_we1,
        out_r_d1,
        p_ZL4demo_0_0_address0,
        p_ZL4demo_0_0_ce0,
        p_ZL4demo_0_0_we0,
        p_ZL4demo_0_0_d0,
        p_ZL4demo_0_0_q0,
        p_ZL4demo_0_1_address0,
        p_ZL4demo_0_1_ce0,
        p_ZL4demo_0_1_we0,
        p_ZL4demo_0_1_d0,
        p_ZL4demo_0_1_q0,
        p_ZL4demo_0_1_address1,
        p_ZL4demo_0_1_ce1,
        p_ZL4demo_0_1_q1,
        p_ZL4demo_0_2_address0,
        p_ZL4demo_0_2_ce0,
        p_ZL4demo_0_2_we0,
        p_ZL4demo_0_2_d0,
        p_ZL4demo_0_2_q0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_we0,
        p_ZL4demo_1_0_d0,
        p_ZL4demo_1_0_q0,
        p_ZL4demo_1_0_address1,
        p_ZL4demo_1_0_ce1,
        p_ZL4demo_1_0_q1,
        p_ZL4demo_1_1_address0,
        p_ZL4demo_1_1_ce0,
        p_ZL4demo_1_1_we0,
        p_ZL4demo_1_1_d0,
        p_ZL4demo_1_1_q0,
        p_ZL4demo_1_1_address1,
        p_ZL4demo_1_1_ce1,
        p_ZL4demo_1_1_q1,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_we0,
        p_ZL4demo_1_2_d0,
        p_ZL4demo_1_2_q0,
        p_ZL4demo_1_2_address1,
        p_ZL4demo_1_2_ce1,
        p_ZL4demo_1_2_q1,
        p_ZL4demo_2_0_address0,
        p_ZL4demo_2_0_ce0,
        p_ZL4demo_2_0_we0,
        p_ZL4demo_2_0_d0,
        p_ZL4demo_2_0_q0,
        p_ZL4demo_2_1_address0,
        p_ZL4demo_2_1_ce0,
        p_ZL4demo_2_1_we0,
        p_ZL4demo_2_1_d0,
        p_ZL4demo_2_1_q0,
        p_ZL4demo_2_1_address1,
        p_ZL4demo_2_1_ce1,
        p_ZL4demo_2_1_q1,
        p_ZL4demo_2_2_address0,
        p_ZL4demo_2_2_ce0,
        p_ZL4demo_2_2_we0,
        p_ZL4demo_2_2_d0,
        p_ZL4demo_2_2_q0
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
input  [1:0] p_read1;
input  [1:0] p_read2;
input  [1:0] p_read3;
input  [1:0] p_read5;
input  [1:0] p_read6;
input  [1:0] p_read7;
output  [13:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [13:0] out_r_address1;
output   out_r_ce1;
output   out_r_we1;
output  [7:0] out_r_d1;
output  [13:0] p_ZL4demo_0_0_address0;
output   p_ZL4demo_0_0_ce0;
output   p_ZL4demo_0_0_we0;
output  [7:0] p_ZL4demo_0_0_d0;
input  [7:0] p_ZL4demo_0_0_q0;
output  [13:0] p_ZL4demo_0_1_address0;
output   p_ZL4demo_0_1_ce0;
output   p_ZL4demo_0_1_we0;
output  [7:0] p_ZL4demo_0_1_d0;
input  [7:0] p_ZL4demo_0_1_q0;
output  [13:0] p_ZL4demo_0_1_address1;
output   p_ZL4demo_0_1_ce1;
input  [7:0] p_ZL4demo_0_1_q1;
output  [13:0] p_ZL4demo_0_2_address0;
output   p_ZL4demo_0_2_ce0;
output   p_ZL4demo_0_2_we0;
output  [7:0] p_ZL4demo_0_2_d0;
input  [7:0] p_ZL4demo_0_2_q0;
output  [13:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
output   p_ZL4demo_1_0_we0;
output  [7:0] p_ZL4demo_1_0_d0;
input  [7:0] p_ZL4demo_1_0_q0;
output  [13:0] p_ZL4demo_1_0_address1;
output   p_ZL4demo_1_0_ce1;
input  [7:0] p_ZL4demo_1_0_q1;
output  [13:0] p_ZL4demo_1_1_address0;
output   p_ZL4demo_1_1_ce0;
output   p_ZL4demo_1_1_we0;
output  [7:0] p_ZL4demo_1_1_d0;
input  [7:0] p_ZL4demo_1_1_q0;
output  [13:0] p_ZL4demo_1_1_address1;
output   p_ZL4demo_1_1_ce1;
input  [7:0] p_ZL4demo_1_1_q1;
output  [13:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
output   p_ZL4demo_1_2_we0;
output  [7:0] p_ZL4demo_1_2_d0;
input  [7:0] p_ZL4demo_1_2_q0;
output  [13:0] p_ZL4demo_1_2_address1;
output   p_ZL4demo_1_2_ce1;
input  [7:0] p_ZL4demo_1_2_q1;
output  [13:0] p_ZL4demo_2_0_address0;
output   p_ZL4demo_2_0_ce0;
output   p_ZL4demo_2_0_we0;
output  [7:0] p_ZL4demo_2_0_d0;
input  [7:0] p_ZL4demo_2_0_q0;
output  [13:0] p_ZL4demo_2_1_address0;
output   p_ZL4demo_2_1_ce0;
output   p_ZL4demo_2_1_we0;
output  [7:0] p_ZL4demo_2_1_d0;
input  [7:0] p_ZL4demo_2_1_q0;
output  [13:0] p_ZL4demo_2_1_address1;
output   p_ZL4demo_2_1_ce1;
input  [7:0] p_ZL4demo_2_1_q1;
output  [13:0] p_ZL4demo_2_2_address0;
output   p_ZL4demo_2_2_ce0;
output   p_ZL4demo_2_2_we0;
output  [7:0] p_ZL4demo_2_2_d0;
input  [7:0] p_ZL4demo_2_2_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[7:0] out_r_d0;
reg[13:0] p_ZL4demo_0_0_address0;
reg p_ZL4demo_0_0_ce0;
reg p_ZL4demo_0_0_we0;
reg[13:0] p_ZL4demo_0_1_address0;
reg p_ZL4demo_0_1_ce0;
reg p_ZL4demo_0_1_we0;
reg[13:0] p_ZL4demo_0_2_address0;
reg p_ZL4demo_0_2_ce0;
reg p_ZL4demo_0_2_we0;
reg[13:0] p_ZL4demo_1_0_address0;
reg p_ZL4demo_1_0_ce0;
reg p_ZL4demo_1_0_we0;
reg[13:0] p_ZL4demo_1_1_address0;
reg p_ZL4demo_1_1_ce0;
reg p_ZL4demo_1_1_we0;
reg[13:0] p_ZL4demo_1_2_address0;
reg p_ZL4demo_1_2_ce0;
reg p_ZL4demo_1_2_we0;
reg[13:0] p_ZL4demo_2_0_address0;
reg p_ZL4demo_2_0_ce0;
reg p_ZL4demo_2_0_we0;
reg[13:0] p_ZL4demo_2_1_address0;
reg p_ZL4demo_2_1_ce0;
reg p_ZL4demo_2_1_we0;
reg[13:0] p_ZL4demo_2_2_address0;
reg p_ZL4demo_2_2_ce0;
reg p_ZL4demo_2_2_we0;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
reg   [7:0] p_ZL4demo_1_1_load_reg_650;
wire    ap_CS_fsm_state14;
reg   [7:0] p_ZL4demo_1_1_load_13_reg_655;
reg   [7:0] p_ZL4demo_0_0_load_reg_660;
wire    ap_CS_fsm_state15;
reg   [7:0] p_ZL4demo_1_0_load_reg_665;
reg   [7:0] p_ZL4demo_0_1_load_reg_670;
reg   [7:0] p_ZL4demo_0_1_load_5_reg_675;
reg   [7:0] p_ZL4demo_0_2_load_reg_680;
reg   [7:0] p_ZL4demo_1_2_load_reg_685;
reg   [7:0] p_ZL4demo_1_0_load_5_reg_690;
reg   [7:0] p_ZL4demo_2_0_load_reg_695;
reg   [7:0] p_ZL4demo_1_1_load_14_reg_700;
reg   [7:0] p_ZL4demo_2_1_load_reg_705;
reg   [7:0] p_ZL4demo_1_1_load_15_reg_710;
reg   [7:0] p_ZL4demo_2_1_load_5_reg_715;
reg   [7:0] p_ZL4demo_1_2_load_5_reg_720;
reg   [7:0] p_ZL4demo_2_2_load_reg_725;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_done;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_idle;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_ready;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_ce0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_d0;
wire   [13:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_address0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_ce0;
wire    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_we0;
wire   [7:0] grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_d0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_ready;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_we0;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_d0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_ready;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_we0;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_d0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_ready;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_we0;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_d0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_ready;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_we0;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_d0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_ready;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_we0;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_d0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_ce0;
wire   [13:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_address0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_ce0;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_ready;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par2_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par2_out_ap_vld;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par1_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par1_out_ap_vld;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_ready;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par2_35_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par2_35_out_ap_vld;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par1_38_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par1_38_out_ap_vld;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_ready;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par2_37_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par2_37_out_ap_vld;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par1_40_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par1_40_out_ap_vld;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_done;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_idle;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_ready;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par2_39_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par2_39_out_ap_vld;
wire   [7:0] grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par1_42_out;
wire    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par1_42_out_ap_vld;
reg    grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    out_r_we0_out;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg;
wire    ap_CS_fsm_state16;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg;
reg    grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    p_ZL4demo_1_1_ce1_local;
wire    ap_CS_fsm_state13;
reg   [13:0] p_ZL4demo_1_1_address1_local;
reg    p_ZL4demo_1_1_ce0_local;
reg   [13:0] p_ZL4demo_1_1_address0_local;
reg    p_ZL4demo_0_0_ce0_local;
reg    p_ZL4demo_1_0_ce1_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_0_1_ce1_local;
reg    p_ZL4demo_0_1_ce0_local;
reg    p_ZL4demo_0_2_ce0_local;
reg    p_ZL4demo_1_2_ce1_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    p_ZL4demo_2_0_ce0_local;
reg    p_ZL4demo_2_1_ce1_local;
reg    p_ZL4demo_2_1_ce0_local;
reg    p_ZL4demo_2_2_ce0_local;
reg    out_r_we1_local;
reg   [7:0] out_r_d1_local;
wire   [7:0] add_ln79_fu_500_p2;
reg    out_r_ce1_local;
reg   [13:0] out_r_address1_local;
reg    out_r_we0_local;
reg   [7:0] out_r_d0_local;
wire   [7:0] add_ln91_fu_513_p2;
reg    out_r_ce0_local;
reg   [13:0] out_r_address0_local;
wire   [7:0] add_ln103_fu_526_p2;
wire   [7:0] add_ln115_fu_539_p2;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_block_state16_on_subcall_done;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg = 1'b0;
#0 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg = 1'b0;
end

real_top_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start),
    .ap_done(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_done),
    .ap_idle(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_idle),
    .ap_ready(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_ready),
    .A_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_address0),
    .A_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_ce0),
    .A_q0(A_q0),
    .p_ZL4demo_0_0_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_address0),
    .p_ZL4demo_0_0_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_ce0),
    .p_ZL4demo_0_0_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_we0),
    .p_ZL4demo_0_0_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_d0),
    .p_ZL4demo_0_1_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_address0),
    .p_ZL4demo_0_1_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_ce0),
    .p_ZL4demo_0_1_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_we0),
    .p_ZL4demo_0_1_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_d0),
    .p_ZL4demo_0_2_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_address0),
    .p_ZL4demo_0_2_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_ce0),
    .p_ZL4demo_0_2_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_we0),
    .p_ZL4demo_0_2_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_d0),
    .p_ZL4demo_1_0_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_address0),
    .p_ZL4demo_1_0_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_ce0),
    .p_ZL4demo_1_0_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_we0),
    .p_ZL4demo_1_0_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_d0),
    .p_ZL4demo_1_1_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_address0),
    .p_ZL4demo_1_1_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_ce0),
    .p_ZL4demo_1_1_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_we0),
    .p_ZL4demo_1_1_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_d0),
    .p_ZL4demo_1_2_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_address0),
    .p_ZL4demo_1_2_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_ce0),
    .p_ZL4demo_1_2_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_we0),
    .p_ZL4demo_1_2_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_d0),
    .p_ZL4demo_2_0_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_address0),
    .p_ZL4demo_2_0_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_ce0),
    .p_ZL4demo_2_0_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_we0),
    .p_ZL4demo_2_0_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_d0),
    .p_ZL4demo_2_1_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_address0),
    .p_ZL4demo_2_1_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_ce0),
    .p_ZL4demo_2_1_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_we0),
    .p_ZL4demo_2_1_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_d0),
    .p_ZL4demo_2_2_address0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_address0),
    .p_ZL4demo_2_2_ce0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_ce0),
    .p_ZL4demo_2_2_we0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_we0),
    .p_ZL4demo_2_2_d0(grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_d0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_ready),
    .out_r_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_address0),
    .out_r_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_ce0),
    .out_r_we0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_we0),
    .out_r_d0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_d0),
    .sext_ln124_1(p_read6),
    .zext_ln124_1(p_read1),
    .zext_ln124(p_read3),
    .sext_ln124_2(p_read5),
    .sext_ln124_3(p_read2),
    .sext_ln124(p_read7),
    .p_ZL4demo_0_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_address0),
    .p_ZL4demo_0_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_ce0),
    .p_ZL4demo_0_0_q0(p_ZL4demo_0_0_q0),
    .p_ZL4demo_0_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_address0),
    .p_ZL4demo_0_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_ce0),
    .p_ZL4demo_0_1_q0(p_ZL4demo_0_1_q0),
    .p_ZL4demo_0_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_address0),
    .p_ZL4demo_0_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_ce0),
    .p_ZL4demo_0_2_q0(p_ZL4demo_0_2_q0),
    .p_ZL4demo_1_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_address0),
    .p_ZL4demo_1_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_ce0),
    .p_ZL4demo_1_0_q0(p_ZL4demo_1_0_q0),
    .p_ZL4demo_1_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_address0),
    .p_ZL4demo_1_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_ce0),
    .p_ZL4demo_1_2_q0(p_ZL4demo_1_2_q0),
    .p_ZL4demo_2_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_address0),
    .p_ZL4demo_2_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_ce0),
    .p_ZL4demo_2_0_q0(p_ZL4demo_2_0_q0),
    .p_ZL4demo_2_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_address0),
    .p_ZL4demo_2_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_ce0),
    .p_ZL4demo_2_1_q0(p_ZL4demo_2_1_q0),
    .p_ZL4demo_2_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_address0),
    .p_ZL4demo_2_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_ce0),
    .p_ZL4demo_2_2_q0(p_ZL4demo_2_2_q0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_ready),
    .out_r_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_address0),
    .out_r_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_ce0),
    .out_r_we0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_we0),
    .out_r_d0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_d0),
    .zext_ln124_1(p_read1),
    .sext_ln124(p_read7),
    .sext_ln124_2(p_read5),
    .sext_ln124_3(p_read2),
    .p_ZL4demo_0_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_address0),
    .p_ZL4demo_0_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_ce0),
    .p_ZL4demo_0_0_q0(p_ZL4demo_0_0_q0),
    .p_ZL4demo_0_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_address0),
    .p_ZL4demo_0_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_ce0),
    .p_ZL4demo_0_1_q0(p_ZL4demo_0_1_q0),
    .p_ZL4demo_1_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_address0),
    .p_ZL4demo_1_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_ce0),
    .p_ZL4demo_1_1_q0(p_ZL4demo_1_1_q0),
    .p_ZL4demo_2_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_address0),
    .p_ZL4demo_2_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_ce0),
    .p_ZL4demo_2_0_q0(p_ZL4demo_2_0_q0),
    .p_ZL4demo_2_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_address0),
    .p_ZL4demo_2_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_ce0),
    .p_ZL4demo_2_1_q0(p_ZL4demo_2_1_q0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_ready),
    .out_r_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_address0),
    .out_r_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_ce0),
    .out_r_we0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_we0),
    .out_r_d0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_d0),
    .zext_ln124(p_read3),
    .sext_ln124(p_read7),
    .sext_ln124_1(p_read6),
    .zext_ln124_1(p_read1),
    .p_ZL4demo_0_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_address0),
    .p_ZL4demo_0_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_ce0),
    .p_ZL4demo_0_1_q0(p_ZL4demo_0_1_q0),
    .p_ZL4demo_0_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_address0),
    .p_ZL4demo_0_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_ce0),
    .p_ZL4demo_0_2_q0(p_ZL4demo_0_2_q0),
    .p_ZL4demo_1_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_address0),
    .p_ZL4demo_1_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_ce0),
    .p_ZL4demo_1_1_q0(p_ZL4demo_1_1_q0),
    .p_ZL4demo_2_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_address0),
    .p_ZL4demo_2_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_ce0),
    .p_ZL4demo_2_1_q0(p_ZL4demo_2_1_q0),
    .p_ZL4demo_2_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_address0),
    .p_ZL4demo_2_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_ce0),
    .p_ZL4demo_2_2_q0(p_ZL4demo_2_2_q0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_ready),
    .out_r_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_address0),
    .out_r_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_ce0),
    .out_r_we0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_we0),
    .out_r_d0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_d0),
    .sext_ln124_1(p_read6),
    .zext_ln124(p_read3),
    .sext_ln124_2(p_read5),
    .sext_ln124(p_read7),
    .p_ZL4demo_0_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_address0),
    .p_ZL4demo_0_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_ce0),
    .p_ZL4demo_0_0_q0(p_ZL4demo_0_0_q0),
    .p_ZL4demo_0_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_address0),
    .p_ZL4demo_0_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_ce0),
    .p_ZL4demo_0_2_q0(p_ZL4demo_0_2_q0),
    .p_ZL4demo_1_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_address0),
    .p_ZL4demo_1_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_ce0),
    .p_ZL4demo_1_0_q0(p_ZL4demo_1_0_q0),
    .p_ZL4demo_1_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_address0),
    .p_ZL4demo_1_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_ce0),
    .p_ZL4demo_1_1_q0(p_ZL4demo_1_1_q0),
    .p_ZL4demo_1_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_address0),
    .p_ZL4demo_1_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_ce0),
    .p_ZL4demo_1_2_q0(p_ZL4demo_1_2_q0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_ready),
    .out_r_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_address0),
    .out_r_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_ce0),
    .out_r_we0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_we0),
    .out_r_d0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_d0),
    .zext_ln124(p_read3),
    .sext_ln124_2(p_read5),
    .sext_ln124_3(p_read2),
    .zext_ln124_1(p_read1),
    .p_ZL4demo_1_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_address0),
    .p_ZL4demo_1_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_ce0),
    .p_ZL4demo_1_0_q0(p_ZL4demo_1_0_q0),
    .p_ZL4demo_1_1_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_address0),
    .p_ZL4demo_1_1_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_ce0),
    .p_ZL4demo_1_1_q0(p_ZL4demo_1_1_q0),
    .p_ZL4demo_1_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_address0),
    .p_ZL4demo_1_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_ce0),
    .p_ZL4demo_1_2_q0(p_ZL4demo_1_2_q0),
    .p_ZL4demo_2_0_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_address0),
    .p_ZL4demo_2_0_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_ce0),
    .p_ZL4demo_2_0_q0(p_ZL4demo_2_0_q0),
    .p_ZL4demo_2_2_address0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_address0),
    .p_ZL4demo_2_2_ce0(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_ce0),
    .p_ZL4demo_2_2_q0(p_ZL4demo_2_2_q0)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_ready),
    .p_ZL4demo_1_0_load_18(p_ZL4demo_1_0_load_reg_665),
    .p_ZL4demo_0_0_load_11(p_ZL4demo_0_0_load_reg_660),
    .p_read7(p_read7),
    .p_ZL4demo_1_1_load_34(p_ZL4demo_1_1_load_reg_650),
    .p_ZL4demo_0_1_load_17(p_ZL4demo_0_1_load_reg_670),
    .p_read5(p_read5),
    .par2_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par2_out),
    .par2_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par2_out_ap_vld),
    .par1_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par1_out),
    .par1_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par1_out_ap_vld)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_ready),
    .p_ZL4demo_1_1_load_36(p_ZL4demo_1_1_load_13_reg_655),
    .p_ZL4demo_0_1_load_18(p_ZL4demo_0_1_load_5_reg_675),
    .sext_ln124_4(p_read6),
    .zext_ln124_2(p_read3),
    .p_ZL4demo_1_2_load_18(p_ZL4demo_1_2_load_reg_685),
    .p_ZL4demo_0_2_load_10(p_ZL4demo_0_2_load_reg_680),
    .p_read7(p_read7),
    .par2_35_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par2_35_out),
    .par2_35_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par2_35_out_ap_vld),
    .par1_38_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par1_38_out),
    .par1_38_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par1_38_out_ap_vld)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_ready),
    .p_ZL4demo_2_0_load_13(p_ZL4demo_2_0_load_reg_695),
    .p_ZL4demo_1_0_load_20(p_ZL4demo_1_0_load_5_reg_690),
    .p_read1(p_read1),
    .p_ZL4demo_2_1_load_19(p_ZL4demo_2_1_load_reg_705),
    .p_ZL4demo_1_1_load_37(p_ZL4demo_1_1_load_14_reg_700),
    .p_read5(p_read5),
    .p_read2(p_read2),
    .par2_37_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par2_37_out),
    .par2_37_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par2_37_out_ap_vld),
    .par1_40_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par1_40_out),
    .par1_40_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par1_40_out_ap_vld)
);

real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1 grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start),
    .ap_done(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_done),
    .ap_idle(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_idle),
    .ap_ready(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_ready),
    .p_ZL4demo_2_1_load_20(p_ZL4demo_2_1_load_5_reg_715),
    .p_ZL4demo_1_1_load_38(p_ZL4demo_1_1_load_15_reg_710),
    .p_read3(p_read3),
    .p_ZL4demo_2_2_load_13(p_ZL4demo_2_2_load_reg_725),
    .p_ZL4demo_1_2_load_19(p_ZL4demo_1_2_load_5_reg_720),
    .p_read1(p_read1),
    .par2_39_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par2_39_out),
    .par2_39_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par2_39_out_ap_vld),
    .par1_42_out(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par1_42_out),
    .par1_42_out_ap_vld(grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par1_42_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_ready == 1'b1)) begin
            grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg <= 1'b1;
        end else if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_ready == 1'b1)) begin
            grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        p_ZL4demo_0_0_load_reg_660 <= p_ZL4demo_0_0_q0;
        p_ZL4demo_0_1_load_5_reg_675 <= p_ZL4demo_0_1_q0;
        p_ZL4demo_0_1_load_reg_670 <= p_ZL4demo_0_1_q1;
        p_ZL4demo_0_2_load_reg_680 <= p_ZL4demo_0_2_q0;
        p_ZL4demo_1_0_load_5_reg_690 <= p_ZL4demo_1_0_q0;
        p_ZL4demo_1_0_load_reg_665 <= p_ZL4demo_1_0_q1;
        p_ZL4demo_1_1_load_14_reg_700 <= p_ZL4demo_1_1_q1;
        p_ZL4demo_1_1_load_15_reg_710 <= p_ZL4demo_1_1_q0;
        p_ZL4demo_1_2_load_5_reg_720 <= p_ZL4demo_1_2_q0;
        p_ZL4demo_1_2_load_reg_685 <= p_ZL4demo_1_2_q1;
        p_ZL4demo_2_0_load_reg_695 <= p_ZL4demo_2_0_q0;
        p_ZL4demo_2_1_load_5_reg_715 <= p_ZL4demo_2_1_q0;
        p_ZL4demo_2_1_load_reg_705 <= p_ZL4demo_2_1_q1;
        p_ZL4demo_2_2_load_reg_725 <= p_ZL4demo_2_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_1_load_13_reg_655 <= p_ZL4demo_1_1_q0;
        p_ZL4demo_1_1_load_reg_650 <= p_ZL4demo_1_1_q1;
    end
end

always @ (*) begin
    if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state16_on_subcall_done)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_r_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_address0;
    end else begin
        out_r_address0 = out_r_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_address0_local = 64'd16383;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_address0_local = 64'd127;
    end else begin
        out_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_address1_local = 64'd16256;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_address1_local = 64'd0;
    end else begin
        out_r_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_r_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_ce0;
    end else begin
        out_r_ce0 = out_r_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        out_r_ce1_local = 1'b1;
    end else begin
        out_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_d0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_d0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_r_d0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_d0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_d0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_d0;
    end else begin
        out_r_d0 = out_r_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_d0_local = add_ln115_fu_539_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_d0_local = add_ln91_fu_513_p2;
    end else begin
        out_r_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_d1_local = add_ln103_fu_526_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_d1_local = add_ln79_fu_500_p2;
    end else begin
        out_r_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_we0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_we0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_r_we0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_we0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_we0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_out_r_we0;
    end else begin
        out_r_we0 = (out_r_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        out_r_we1_local = 1'b1;
    end else begin
        out_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_0_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_0_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_0_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_address0;
    end else begin
        p_ZL4demo_0_0_address0 = 14'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_0_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_0_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_0_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_ce0;
    end else begin
        p_ZL4demo_0_0_ce0 = p_ZL4demo_0_0_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_0_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_we0;
    end else begin
        p_ZL4demo_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_0_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_0_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_1_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_address0;
    end else begin
        p_ZL4demo_0_1_address0 = 14'd125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_0_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_0_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_1_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_ce0;
    end else begin
        p_ZL4demo_0_1_ce0 = p_ZL4demo_0_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_0_1_ce1_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_1_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_we0;
    end else begin
        p_ZL4demo_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_0_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_0_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_2_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_address0;
    end else begin
        p_ZL4demo_0_2_address0 = 14'd125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_0_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_0_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_0_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_2_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_ce0;
    end else begin
        p_ZL4demo_0_2_ce0 = p_ZL4demo_0_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_0_2_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_we0;
    end else begin
        p_ZL4demo_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_1_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_0_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_address0;
    end else begin
        p_ZL4demo_1_0_address0 = 14'd16000;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_1_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_0_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_ce0;
    end else begin
        p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_0_ce1_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_0_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_we0;
    end else begin
        p_ZL4demo_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_1_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_1_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_1_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_address0;
    end else begin
        p_ZL4demo_1_1_address0 = p_ZL4demo_1_1_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_1_address0_local = 14'd16125;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_ZL4demo_1_1_address0_local = 14'd125;
    end else begin
        p_ZL4demo_1_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_1_address1_local = 14'd16000;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_ZL4demo_1_1_address1_local = 14'd0;
    end else begin
        p_ZL4demo_1_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_1_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_1_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_1_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_ce0;
    end else begin
        p_ZL4demo_1_1_ce0 = p_ZL4demo_1_1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14))) begin
        p_ZL4demo_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14))) begin
        p_ZL4demo_1_1_ce1_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_1_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_we0;
    end else begin
        p_ZL4demo_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_1_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_2_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_address0;
    end else begin
        p_ZL4demo_1_2_address0 = 14'd16125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_1_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_ZL4demo_1_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_p_ZL4demo_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_1_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_2_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_ce0;
    end else begin
        p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_1_2_ce1_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_1_2_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_we0;
    end else begin
        p_ZL4demo_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_2_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_2_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_0_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_0_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_address0;
    end else begin
        p_ZL4demo_2_0_address0 = 14'd16000;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_2_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_2_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_0_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_0_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_ce0;
    end else begin
        p_ZL4demo_2_0_ce0 = p_ZL4demo_2_0_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_2_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_0_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_we0;
    end else begin
        p_ZL4demo_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_2_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_2_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_1_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_1_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_address0;
    end else begin
        p_ZL4demo_2_1_address0 = 14'd16125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_2_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZL4demo_2_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_p_ZL4demo_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_1_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_1_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_ce0;
    end else begin
        p_ZL4demo_2_1_ce0 = p_ZL4demo_2_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_2_1_ce1_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_1_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_we0;
    end else begin
        p_ZL4demo_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_2_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_2_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_2_address0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_2_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_address0;
    end else begin
        p_ZL4demo_2_2_address0 = 14'd16125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_ZL4demo_2_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_p_ZL4demo_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_ZL4demo_2_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_p_ZL4demo_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZL4demo_2_2_ce0 = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_p_ZL4demo_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_2_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_ce0;
    end else begin
        p_ZL4demo_2_2_ce0 = p_ZL4demo_2_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZL4demo_2_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL4demo_2_2_we0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_we0;
    end else begin
        p_ZL4demo_2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_address0;

assign A_ce0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_A_ce0;

assign add_ln103_fu_526_p2 = (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par2_37_out + grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_par1_40_out);

assign add_ln115_fu_539_p2 = (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par2_39_out + grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_par1_42_out);

assign add_ln79_fu_500_p2 = (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par2_out + grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_par1_out);

assign add_ln91_fu_513_p2 = (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par2_35_out + grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_par1_38_out);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state16_on_subcall_done = ((grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_done == 1'b0) | (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_done == 1'b0) | (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_done == 1'b0) | (grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_done == 1'b0));
end

assign grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_111_1_fu_478_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6_fu_316_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_151_7_fu_350_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_155_8_fu_370_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_159_9_fu_390_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_163_10_fu_410_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_75_1_fu_430_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_87_1_fu_445_ap_start_reg;

assign grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start = grp_img_sharp_128_128_7_Pipeline_VITIS_LOOP_99_1_fu_461_ap_start_reg;

assign out_r_address1 = out_r_address1_local;

assign out_r_ce1 = out_r_ce1_local;

assign out_r_d1 = out_r_d1_local;

assign out_r_we0_out = out_r_we0_local;

assign out_r_we1 = out_r_we1_local;

assign p_ZL4demo_0_0_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_0_d0;

assign p_ZL4demo_0_1_address1 = 14'd0;

assign p_ZL4demo_0_1_ce1 = p_ZL4demo_0_1_ce1_local;

assign p_ZL4demo_0_1_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_1_d0;

assign p_ZL4demo_0_2_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_0_2_d0;

assign p_ZL4demo_1_0_address1 = 14'd0;

assign p_ZL4demo_1_0_ce1 = p_ZL4demo_1_0_ce1_local;

assign p_ZL4demo_1_0_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_0_d0;

assign p_ZL4demo_1_1_address1 = p_ZL4demo_1_1_address1_local;

assign p_ZL4demo_1_1_ce1 = p_ZL4demo_1_1_ce1_local;

assign p_ZL4demo_1_1_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_1_d0;

assign p_ZL4demo_1_2_address1 = 14'd125;

assign p_ZL4demo_1_2_ce1 = p_ZL4demo_1_2_ce1_local;

assign p_ZL4demo_1_2_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_1_2_d0;

assign p_ZL4demo_2_0_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_0_d0;

assign p_ZL4demo_2_1_address1 = 14'd16000;

assign p_ZL4demo_2_1_ce1 = p_ZL4demo_2_1_ce1_local;

assign p_ZL4demo_2_1_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_1_d0;

assign p_ZL4demo_2_2_d0 = grp_img_sharp7_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOO_fu_292_p_ZL4demo_2_2_d0;

endmodule //real_top_img_sharp_128_128_7
