// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_64_64_7_Pipeline_VITIS_LOOP_159_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        sext_ln124_1,
        zext_ln124,
        sext_ln124_2,
        sext_ln124,
        p_ZL4demo_0_0_address0,
        p_ZL4demo_0_0_ce0,
        p_ZL4demo_0_0_q0,
        p_ZL4demo_0_2_address0,
        p_ZL4demo_0_2_ce0,
        p_ZL4demo_0_2_q0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_q0,
        p_ZL4demo_1_1_address0,
        p_ZL4demo_1_1_ce0,
        p_ZL4demo_1_1_q0,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
input  [1:0] sext_ln124_1;
input  [1:0] zext_ln124;
input  [1:0] sext_ln124_2;
input  [1:0] sext_ln124;
output  [11:0] p_ZL4demo_0_0_address0;
output   p_ZL4demo_0_0_ce0;
input  [7:0] p_ZL4demo_0_0_q0;
output  [11:0] p_ZL4demo_0_2_address0;
output   p_ZL4demo_0_2_ce0;
input  [7:0] p_ZL4demo_0_2_q0;
output  [11:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
input  [7:0] p_ZL4demo_1_0_q0;
output  [11:0] p_ZL4demo_1_1_address0;
output   p_ZL4demo_1_1_ce0;
input  [7:0] p_ZL4demo_1_1_q0;
output  [11:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
input  [7:0] p_ZL4demo_1_2_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln159_fu_178_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [7:0] sext_ln124_cast_fu_154_p1;
reg  signed [7:0] sext_ln124_cast_reg_246;
wire    ap_block_pp0_stage0_11001;
wire  signed [7:0] sext_ln124_2_cast_fu_158_p1;
reg  signed [7:0] sext_ln124_2_cast_reg_251;
wire   [7:0] zext_ln124_cast_fu_162_p1;
reg   [7:0] zext_ln124_cast_reg_256;
wire  signed [7:0] sext_ln124_1_cast_fu_166_p1;
reg  signed [7:0] sext_ln124_1_cast_reg_261;
wire   [5:0] add_ln160_fu_184_p2;
reg   [5:0] add_ln160_reg_270;
reg   [5:0] add_ln160_reg_270_pp0_iter1_reg;
reg   [5:0] add_ln160_reg_270_pp0_iter2_reg;
reg   [5:0] add_ln160_reg_270_pp0_iter3_reg;
reg   [5:0] add_ln160_reg_270_pp0_iter4_reg;
wire   [63:0] zext_ln159_fu_190_p1;
reg   [63:0] zext_ln159_reg_275;
reg   [63:0] zext_ln159_reg_275_pp0_iter1_reg;
reg   [63:0] zext_ln159_reg_275_pp0_iter2_reg;
wire   [7:0] mul_ln53_fu_201_p2;
reg  signed [7:0] mul_ln53_reg_312;
wire   [7:0] mul_ln53_1_fu_206_p2;
reg   [7:0] mul_ln53_1_reg_317;
wire   [7:0] sub_ln53_fu_215_p2;
reg   [7:0] sub_ln53_reg_327;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_fu_221_p1;
reg   [5:0] j_fu_48;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_4;
reg    p_ZL4demo_0_2_ce0_local;
reg    p_ZL4demo_1_1_ce0_local;
reg    p_ZL4demo_0_0_ce0_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    out_r_we0_local;
reg    out_r_ce0_local;
wire  signed [1:0] mul_ln53_fu_201_p1;
wire   [1:0] mul_ln53_1_fu_206_p1;
wire  signed [7:0] grp_fu_232_p3;
wire  signed [7:0] add_ln53_2_fu_211_p1;
wire   [7:0] grp_fu_225_p3;
(* use_dsp48 = "no" *) wire   [7:0] add_ln53_2_fu_211_p2;
wire  signed [1:0] grp_fu_225_p1;
wire  signed [1:0] grp_fu_232_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_fu_48 = 6'd0;
#0 ap_done_reg = 1'b0;
end

real_top_mul_8s_2s_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mul_8s_2s_8_1_1_U79(
    .din0(p_ZL4demo_1_0_q0),
    .din1(mul_ln53_fu_201_p1),
    .dout(mul_ln53_fu_201_p2)
);

real_top_mul_8s_2ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mul_8s_2ns_8_1_1_U80(
    .din0(p_ZL4demo_0_0_q0),
    .din1(mul_ln53_1_fu_206_p1),
    .dout(mul_ln53_1_fu_206_p2)
);

real_top_mac_muladd_8s_2s_8ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_2s_8ns_8_4_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL4demo_0_2_q0),
    .din1(grp_fu_225_p1),
    .din2(mul_ln53_1_reg_317),
    .ce(1'b1),
    .dout(grp_fu_225_p3)
);

real_top_mac_muladd_8s_2s_8s_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_2s_8s_8_4_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL4demo_1_1_q0),
    .din1(grp_fu_232_p1),
    .din2(mul_ln53_reg_312),
    .ce(1'b1),
    .dout(grp_fu_232_p3)
);

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln159_fu_178_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_48 <= add_ln160_fu_184_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_48 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln160_reg_270 <= add_ln160_fu_184_p2;
        add_ln160_reg_270_pp0_iter1_reg <= add_ln160_reg_270;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        sext_ln124_1_cast_reg_261 <= sext_ln124_1_cast_fu_166_p1;
        sext_ln124_2_cast_reg_251 <= sext_ln124_2_cast_fu_158_p1;
        sext_ln124_cast_reg_246 <= sext_ln124_cast_fu_154_p1;
        zext_ln124_cast_reg_256[1 : 0] <= zext_ln124_cast_fu_162_p1[1 : 0];
        zext_ln159_reg_275[5 : 0] <= zext_ln159_fu_190_p1[5 : 0];
        zext_ln159_reg_275_pp0_iter1_reg[5 : 0] <= zext_ln159_reg_275[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln160_reg_270_pp0_iter2_reg <= add_ln160_reg_270_pp0_iter1_reg;
        add_ln160_reg_270_pp0_iter3_reg <= add_ln160_reg_270_pp0_iter2_reg;
        add_ln160_reg_270_pp0_iter4_reg <= add_ln160_reg_270_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        mul_ln53_1_reg_317 <= mul_ln53_1_fu_206_p2;
        mul_ln53_reg_312 <= mul_ln53_fu_201_p2;
        sub_ln53_reg_327 <= sub_ln53_fu_215_p2;
        zext_ln159_reg_275_pp0_iter2_reg[5 : 0] <= zext_ln159_reg_275_pp0_iter1_reg[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln159_fu_178_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_4 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_4 = j_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_184_p2 = (ap_sig_allocacmp_j_4 + 6'd1);

assign add_ln53_2_fu_211_p1 = grp_fu_225_p3;

assign add_ln53_2_fu_211_p2 = ($signed(grp_fu_232_p3) + $signed(add_ln53_2_fu_211_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_225_p1 = sext_ln124_2_cast_reg_251;

assign grp_fu_232_p1 = sext_ln124_cast_reg_246;

assign icmp_ln159_fu_178_p2 = ((ap_sig_allocacmp_j_4 == 6'd62) ? 1'b1 : 1'b0);

assign mul_ln53_1_fu_206_p1 = zext_ln124_cast_reg_256;

assign mul_ln53_fu_201_p1 = sext_ln124_1_cast_reg_261;

assign out_r_address0 = zext_ln160_fu_221_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = sub_ln53_reg_327;

assign out_r_we0 = out_r_we0_local;

assign p_ZL4demo_0_0_address0 = zext_ln159_reg_275;

assign p_ZL4demo_0_0_ce0 = p_ZL4demo_0_0_ce0_local;

assign p_ZL4demo_0_2_address0 = zext_ln159_fu_190_p1;

assign p_ZL4demo_0_2_ce0 = p_ZL4demo_0_2_ce0_local;

assign p_ZL4demo_1_0_address0 = zext_ln159_reg_275;

assign p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;

assign p_ZL4demo_1_1_address0 = zext_ln159_fu_190_p1;

assign p_ZL4demo_1_1_ce0 = p_ZL4demo_1_1_ce0_local;

assign p_ZL4demo_1_2_address0 = zext_ln159_reg_275_pp0_iter2_reg;

assign p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;

assign sext_ln124_1_cast_fu_166_p1 = $signed(sext_ln124_1);

assign sext_ln124_2_cast_fu_158_p1 = $signed(sext_ln124_2);

assign sext_ln124_cast_fu_154_p1 = $signed(sext_ln124);

assign sub_ln53_fu_215_p2 = (add_ln53_2_fu_211_p2 - p_ZL4demo_1_2_q0);

assign zext_ln124_cast_fu_162_p1 = zext_ln124;

assign zext_ln159_fu_190_p1 = ap_sig_allocacmp_j_4;

assign zext_ln160_fu_221_p1 = add_ln160_reg_270_pp0_iter4_reg;

always @ (posedge ap_clk) begin
    zext_ln124_cast_reg_256[7:2] <= 6'b000000;
    zext_ln159_reg_275[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln159_reg_275_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln159_reg_275_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //real_top_img_sharp_64_64_7_Pipeline_VITIS_LOOP_159_9
