// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_32_32_Pipeline_VITIS_LOOP_87_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL4demo_1_1_load_21,
        p_ZL4demo_0_1_load_12,
        p_ZL4demo_1_2_load_11,
        p_ZL4demo_0_2_load,
        par2_20_out,
        par2_20_out_ap_vld,
        par1_21_out,
        par1_21_out_ap_vld,
        laplacian_0_address0,
        laplacian_0_ce0,
        laplacian_0_q0,
        laplacian_1_address0,
        laplacian_1_ce0,
        laplacian_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_ZL4demo_1_1_load_21;
input  [7:0] p_ZL4demo_0_1_load_12;
input  [7:0] p_ZL4demo_1_2_load_11;
input  [7:0] p_ZL4demo_0_2_load;
output  [7:0] par2_20_out;
output   par2_20_out_ap_vld;
output  [7:0] par1_21_out;
output   par1_21_out_ap_vld;
output  [1:0] laplacian_0_address0;
output   laplacian_0_ce0;
input  [0:0] laplacian_0_q0;
output  [1:0] laplacian_1_address0;
output   laplacian_1_ce0;
input  [2:0] laplacian_1_q0;

reg ap_idle;
reg par2_20_out_ap_vld;
reg par1_21_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln87_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln87_reg_282;
reg   [0:0] icmp_ln87_reg_282_pp0_iter1_reg;
reg   [0:0] icmp_ln87_reg_282_pp0_iter2_reg;
wire   [0:0] icmp_ln88_fu_162_p2;
reg   [0:0] icmp_ln88_reg_286;
wire   [63:0] zext_ln88_fu_156_p1;
wire    ap_block_pp0_stage0;
reg   [7:0] par1_fu_50;
wire   [7:0] par1_10_fu_195_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [7:0] par2_fu_54;
wire   [7:0] grp_fu_230_p3;
reg   [7:0] ap_sig_allocacmp_par2_load_10;
reg   [1:0] i_fu_58;
wire   [1:0] add_ln88_fu_150_p2;
reg   [1:0] ap_sig_allocacmp_i_14;
wire    ap_block_pp0_stage0_01001;
reg    laplacian_0_ce0_local;
reg    laplacian_1_ce0_local;
wire   [7:0] select_ln88_fu_176_p3;
wire   [7:0] select_ln88_2_fu_181_p3;
wire   [7:0] and_ln88_fu_189_p2;
wire  signed [7:0] grp_fu_230_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 par1_fu_50 = 8'd0;
#0 par2_fu_54 = 8'd0;
#0 i_fu_58 = 2'd0;
#0 ap_done_reg = 1'b0;
end

real_top_mac_muladd_8s_3s_8ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_3s_8ns_8_4_1_U220(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_230_p0),
    .din1(laplacian_1_q0),
    .din2(ap_sig_allocacmp_par2_load_10),
    .ce(1'b1),
    .dout(grp_fu_230_p3)
);

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_58 <= add_ln88_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            par1_fu_50 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            par1_fu_50 <= par1_10_fu_195_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            par2_fu_54 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            par2_fu_54 <= grp_fu_230_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln87_reg_282 <= icmp_ln87_fu_144_p2;
        icmp_ln87_reg_282_pp0_iter1_reg <= icmp_ln87_reg_282;
        icmp_ln88_reg_286 <= icmp_ln88_fu_162_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln87_reg_282_pp0_iter2_reg <= icmp_ln87_reg_282_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln87_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_14 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_14 = i_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_par2_load_10 = grp_fu_230_p3;
    end else begin
        ap_sig_allocacmp_par2_load_10 = par2_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        laplacian_0_ce0_local = 1'b1;
    end else begin
        laplacian_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        laplacian_1_ce0_local = 1'b1;
    end else begin
        laplacian_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln87_reg_282_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        par1_21_out_ap_vld = 1'b1;
    end else begin
        par1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln87_reg_282_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        par2_20_out_ap_vld = 1'b1;
    end else begin
        par2_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln88_fu_150_p2 = (ap_sig_allocacmp_i_14 + 2'd1);

assign and_ln88_fu_189_p2 = (select_ln88_fu_176_p3 & select_ln88_2_fu_181_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_230_p0 = ((icmp_ln88_reg_286[0:0] == 1'b1) ? p_ZL4demo_1_2_load_11 : p_ZL4demo_0_2_load);

assign icmp_ln87_fu_144_p2 = ((ap_sig_allocacmp_i_14 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_162_p2 = ((ap_sig_allocacmp_i_14 == 2'd1) ? 1'b1 : 1'b0);

assign laplacian_0_address0 = zext_ln88_fu_156_p1;

assign laplacian_0_ce0 = laplacian_0_ce0_local;

assign laplacian_1_address0 = zext_ln88_fu_156_p1;

assign laplacian_1_ce0 = laplacian_1_ce0_local;

assign par1_10_fu_195_p2 = (and_ln88_fu_189_p2 + par1_fu_50);

assign par1_21_out = par1_fu_50;

assign par2_20_out = par2_fu_54;

assign select_ln88_2_fu_181_p3 = ((laplacian_0_q0[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln88_fu_176_p3 = ((icmp_ln88_reg_286[0:0] == 1'b1) ? p_ZL4demo_1_1_load_21 : p_ZL4demo_0_1_load_12);

assign zext_ln88_fu_156_p1 = add_ln88_fu_150_p2;

endmodule //real_top_img_sharp_32_32_Pipeline_VITIS_LOOP_87_1
