// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        sext_ln124_1,
        zext_ln124_1,
        zext_ln124,
        sext_ln124_2,
        sext_ln124_3,
        sext_ln124,
        p_ZL4demo_0_0_address0,
        p_ZL4demo_0_0_ce0,
        p_ZL4demo_0_0_q0,
        p_ZL4demo_0_1_address0,
        p_ZL4demo_0_1_ce0,
        p_ZL4demo_0_1_q0,
        p_ZL4demo_0_2_address0,
        p_ZL4demo_0_2_ce0,
        p_ZL4demo_0_2_q0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_q0,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_q0,
        p_ZL4demo_2_0_address0,
        p_ZL4demo_2_0_ce0,
        p_ZL4demo_2_0_q0,
        p_ZL4demo_2_1_address0,
        p_ZL4demo_2_1_ce0,
        p_ZL4demo_2_1_q0,
        p_ZL4demo_2_2_address0,
        p_ZL4demo_2_2_ce0,
        p_ZL4demo_2_2_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
input  [1:0] sext_ln124_1;
input  [1:0] zext_ln124_1;
input  [1:0] zext_ln124;
input  [1:0] sext_ln124_2;
input  [1:0] sext_ln124_3;
input  [1:0] sext_ln124;
output  [13:0] p_ZL4demo_0_0_address0;
output   p_ZL4demo_0_0_ce0;
input  [7:0] p_ZL4demo_0_0_q0;
output  [13:0] p_ZL4demo_0_1_address0;
output   p_ZL4demo_0_1_ce0;
input  [7:0] p_ZL4demo_0_1_q0;
output  [13:0] p_ZL4demo_0_2_address0;
output   p_ZL4demo_0_2_ce0;
input  [7:0] p_ZL4demo_0_2_q0;
output  [13:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
input  [7:0] p_ZL4demo_1_0_q0;
output  [13:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
input  [7:0] p_ZL4demo_1_2_q0;
output  [13:0] p_ZL4demo_2_0_address0;
output   p_ZL4demo_2_0_ce0;
input  [7:0] p_ZL4demo_2_0_q0;
output  [13:0] p_ZL4demo_2_1_address0;
output   p_ZL4demo_2_1_ce0;
input  [7:0] p_ZL4demo_2_1_q0;
output  [13:0] p_ZL4demo_2_2_address0;
output   p_ZL4demo_2_2_ce0;
input  [7:0] p_ZL4demo_2_2_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln143_fu_275_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [7:0] sext_ln124_cast_fu_233_p1;
reg  signed [7:0] sext_ln124_cast_reg_456;
wire    ap_block_pp0_stage0_11001;
wire  signed [7:0] sext_ln124_3_cast_fu_237_p1;
reg  signed [7:0] sext_ln124_3_cast_reg_461;
wire  signed [7:0] sext_ln124_2_cast_fu_241_p1;
reg  signed [7:0] sext_ln124_2_cast_reg_466;
wire   [7:0] zext_ln124_cast_fu_245_p1;
reg   [7:0] zext_ln124_cast_reg_471;
wire   [7:0] zext_ln124_1_cast_fu_249_p1;
reg   [7:0] zext_ln124_1_cast_reg_476;
wire  signed [7:0] sext_ln124_1_cast_fu_253_p1;
reg  signed [7:0] sext_ln124_1_cast_reg_481;
reg   [6:0] i_load_reg_490;
reg   [6:0] i_load_reg_490_pp0_iter1_reg;
reg   [6:0] i_load_reg_490_pp0_iter2_reg;
reg   [6:0] i_load_reg_490_pp0_iter3_reg;
reg   [6:0] i_load_reg_490_pp0_iter4_reg;
wire   [0:0] icmp_ln145_fu_293_p2;
reg   [0:0] icmp_ln145_reg_495;
reg   [0:0] icmp_ln145_reg_495_pp0_iter1_reg;
reg   [0:0] icmp_ln145_reg_495_pp0_iter2_reg;
reg   [0:0] icmp_ln145_reg_495_pp0_iter3_reg;
reg   [0:0] icmp_ln145_reg_495_pp0_iter4_reg;
wire   [6:0] indvars_iv_next3029_fu_307_p2;
reg   [6:0] indvars_iv_next3029_reg_500;
reg   [6:0] indvars_iv_next3029_reg_500_pp0_iter1_reg;
reg   [6:0] indvars_iv_next3029_reg_500_pp0_iter2_reg;
reg   [6:0] indvars_iv_next3029_reg_500_pp0_iter3_reg;
reg   [6:0] indvars_iv_next3029_reg_500_pp0_iter4_reg;
wire   [63:0] zext_ln11_fu_329_p1;
reg   [63:0] zext_ln11_reg_505;
reg   [63:0] zext_ln11_reg_505_pp0_iter1_reg;
reg   [63:0] zext_ln11_reg_505_pp0_iter2_reg;
wire   [6:0] add_ln147_fu_336_p2;
reg   [6:0] add_ln147_reg_529;
reg   [6:0] add_ln147_reg_529_pp0_iter1_reg;
reg   [6:0] add_ln147_reg_529_pp0_iter2_reg;
reg   [6:0] add_ln147_reg_529_pp0_iter3_reg;
reg   [6:0] add_ln147_reg_529_pp0_iter4_reg;
wire   [7:0] mul_ln15_fu_357_p2;
reg  signed [7:0] mul_ln15_reg_564;
wire   [7:0] mul_ln15_1_fu_362_p2;
reg   [7:0] mul_ln15_1_reg_569;
wire   [7:0] mul_ln15_2_fu_367_p2;
reg   [7:0] mul_ln15_2_reg_574;
reg   [7:0] p_ZL4demo_2_2_load_reg_589;
(* use_dsp48 = "no" *) wire   [7:0] add_ln15_10_fu_372_p2;
reg   [7:0] add_ln15_10_reg_594;
(* use_dsp48 = "no" *) wire   [7:0] add_ln15_13_fu_377_p2;
reg   [7:0] add_ln15_13_reg_599;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln147_fu_399_p1;
reg   [6:0] j_fu_68;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_72;
wire   [6:0] select_ln143_9_fu_313_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [13:0] indvar_flatten42_fu_76;
wire   [13:0] add_ln143_fu_281_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten42_load;
reg    p_ZL4demo_0_2_ce0_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    p_ZL4demo_2_1_ce0_local;
reg    p_ZL4demo_0_1_ce0_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_2_0_ce0_local;
reg    p_ZL4demo_0_0_ce0_local;
reg    p_ZL4demo_2_2_ce0_local;
reg    out_r_we0_local;
wire   [7:0] sub_ln15_fu_408_p2;
reg    out_r_ce0_local;
wire   [6:0] select_ln143_fu_299_p3;
wire   [13:0] tmp_s_fu_321_p3;
wire  signed [1:0] mul_ln15_fu_357_p1;
wire   [1:0] mul_ln15_1_fu_362_p1;
wire   [1:0] mul_ln15_2_fu_367_p1;
wire  signed [7:0] add_ln15_10_fu_372_p0;
wire   [7:0] grp_fu_421_p3;
wire  signed [7:0] grp_fu_428_p3;
wire  signed [7:0] add_ln15_13_fu_377_p1;
wire   [7:0] grp_fu_414_p3;
wire   [6:0] indvars_iv_next30_mid1_fu_381_p2;
wire   [6:0] select_ln143_10_fu_386_p3;
wire   [13:0] tmp_21_fu_392_p3;
wire   [7:0] add_ln15_14_fu_404_p2;
wire  signed [1:0] grp_fu_414_p1;
wire  signed [1:0] grp_fu_421_p1;
wire  signed [1:0] grp_fu_428_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_fu_68 = 7'd0;
#0 i_fu_72 = 7'd0;
#0 indvar_flatten42_fu_76 = 14'd0;
#0 ap_done_reg = 1'b0;
end

real_top_mul_8s_2s_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mul_8s_2s_8_1_1_U24(
    .din0(p_ZL4demo_2_0_q0),
    .din1(mul_ln15_fu_357_p1),
    .dout(mul_ln15_fu_357_p2)
);

real_top_mul_8s_2ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mul_8s_2ns_8_1_1_U25(
    .din0(p_ZL4demo_0_1_q0),
    .din1(mul_ln15_1_fu_362_p1),
    .dout(mul_ln15_1_fu_362_p2)
);

real_top_mul_8s_2ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mul_8s_2ns_8_1_1_U26(
    .din0(p_ZL4demo_1_0_q0),
    .din1(mul_ln15_2_fu_367_p1),
    .dout(mul_ln15_2_fu_367_p2)
);

real_top_mac_muladd_8s_2s_8ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_2s_8ns_8_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL4demo_1_2_q0),
    .din1(grp_fu_414_p1),
    .din2(mul_ln15_2_reg_574),
    .ce(1'b1),
    .dout(grp_fu_414_p3)
);

real_top_mac_muladd_8s_2s_8ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_2s_8ns_8_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL4demo_0_2_q0),
    .din1(grp_fu_421_p1),
    .din2(mul_ln15_1_reg_569),
    .ce(1'b1),
    .dout(grp_fu_421_p3)
);

real_top_mac_muladd_8s_2s_8s_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_8s_2s_8s_8_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL4demo_2_1_q0),
    .din1(grp_fu_428_p1),
    .din2(mul_ln15_reg_564),
    .ce(1'b1),
    .dout(grp_fu_428_p3)
);

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_275_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_72 <= select_ln143_9_fu_313_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_275_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten42_fu_76 <= add_ln143_fu_281_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten42_fu_76 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_275_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_68 <= add_ln147_fu_336_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_68 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln147_reg_529 <= add_ln147_fu_336_p2;
        add_ln147_reg_529_pp0_iter1_reg <= add_ln147_reg_529;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_load_reg_490 <= ap_sig_allocacmp_i_load;
        i_load_reg_490_pp0_iter1_reg <= i_load_reg_490;
        icmp_ln145_reg_495 <= icmp_ln145_fu_293_p2;
        icmp_ln145_reg_495_pp0_iter1_reg <= icmp_ln145_reg_495;
        indvars_iv_next3029_reg_500 <= indvars_iv_next3029_fu_307_p2;
        indvars_iv_next3029_reg_500_pp0_iter1_reg <= indvars_iv_next3029_reg_500;
        sext_ln124_1_cast_reg_481 <= sext_ln124_1_cast_fu_253_p1;
        sext_ln124_2_cast_reg_466 <= sext_ln124_2_cast_fu_241_p1;
        sext_ln124_3_cast_reg_461 <= sext_ln124_3_cast_fu_237_p1;
        sext_ln124_cast_reg_456 <= sext_ln124_cast_fu_233_p1;
        zext_ln11_reg_505[13 : 0] <= zext_ln11_fu_329_p1[13 : 0];
        zext_ln11_reg_505_pp0_iter1_reg[13 : 0] <= zext_ln11_reg_505[13 : 0];
        zext_ln124_1_cast_reg_476[1 : 0] <= zext_ln124_1_cast_fu_249_p1[1 : 0];
        zext_ln124_cast_reg_471[1 : 0] <= zext_ln124_cast_fu_245_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln147_reg_529_pp0_iter2_reg <= add_ln147_reg_529_pp0_iter1_reg;
        add_ln147_reg_529_pp0_iter3_reg <= add_ln147_reg_529_pp0_iter2_reg;
        add_ln147_reg_529_pp0_iter4_reg <= add_ln147_reg_529_pp0_iter3_reg;
        add_ln15_10_reg_594 <= add_ln15_10_fu_372_p2;
        add_ln15_13_reg_599 <= add_ln15_13_fu_377_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        i_load_reg_490_pp0_iter2_reg <= i_load_reg_490_pp0_iter1_reg;
        i_load_reg_490_pp0_iter3_reg <= i_load_reg_490_pp0_iter2_reg;
        i_load_reg_490_pp0_iter4_reg <= i_load_reg_490_pp0_iter3_reg;
        icmp_ln145_reg_495_pp0_iter2_reg <= icmp_ln145_reg_495_pp0_iter1_reg;
        icmp_ln145_reg_495_pp0_iter3_reg <= icmp_ln145_reg_495_pp0_iter2_reg;
        icmp_ln145_reg_495_pp0_iter4_reg <= icmp_ln145_reg_495_pp0_iter3_reg;
        indvars_iv_next3029_reg_500_pp0_iter2_reg <= indvars_iv_next3029_reg_500_pp0_iter1_reg;
        indvars_iv_next3029_reg_500_pp0_iter3_reg <= indvars_iv_next3029_reg_500_pp0_iter2_reg;
        indvars_iv_next3029_reg_500_pp0_iter4_reg <= indvars_iv_next3029_reg_500_pp0_iter3_reg;
        mul_ln15_1_reg_569 <= mul_ln15_1_fu_362_p2;
        mul_ln15_2_reg_574 <= mul_ln15_2_fu_367_p2;
        mul_ln15_reg_564 <= mul_ln15_fu_357_p2;
        p_ZL4demo_2_2_load_reg_589 <= p_ZL4demo_2_2_q0;
        zext_ln11_reg_505_pp0_iter2_reg[13 : 0] <= zext_ln11_reg_505_pp0_iter1_reg[13 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_275_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten42_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten42_load = indvar_flatten42_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL4demo_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_2_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL4demo_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL4demo_2_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln143_fu_281_p2 = (ap_sig_allocacmp_indvar_flatten42_load + 14'd1);

assign add_ln147_fu_336_p2 = (select_ln143_fu_299_p3 + 7'd1);

assign add_ln15_10_fu_372_p0 = grp_fu_421_p3;

assign add_ln15_10_fu_372_p2 = ($signed(add_ln15_10_fu_372_p0) + $signed(p_ZL4demo_0_0_q0));

assign add_ln15_13_fu_377_p1 = grp_fu_414_p3;

assign add_ln15_13_fu_377_p2 = ($signed(grp_fu_428_p3) + $signed(add_ln15_13_fu_377_p1));

assign add_ln15_14_fu_404_p2 = (add_ln15_13_reg_599 + add_ln15_10_reg_594);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_414_p1 = sext_ln124_2_cast_reg_466;

assign grp_fu_421_p1 = sext_ln124_3_cast_reg_461;

assign grp_fu_428_p1 = sext_ln124_cast_reg_456;

assign icmp_ln143_fu_275_p2 = ((ap_sig_allocacmp_indvar_flatten42_load == 14'd15876) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_293_p2 = ((ap_sig_allocacmp_j_load == 7'd126) ? 1'b1 : 1'b0);

assign indvars_iv_next3029_fu_307_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign indvars_iv_next30_mid1_fu_381_p2 = (i_load_reg_490_pp0_iter4_reg + 7'd2);

assign mul_ln15_1_fu_362_p1 = zext_ln124_1_cast_reg_476;

assign mul_ln15_2_fu_367_p1 = zext_ln124_cast_reg_471;

assign mul_ln15_fu_357_p1 = sext_ln124_1_cast_reg_481;

assign out_r_address0 = zext_ln147_fu_399_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = sub_ln15_fu_408_p2;

assign out_r_we0 = out_r_we0_local;

assign p_ZL4demo_0_0_address0 = zext_ln11_reg_505_pp0_iter2_reg;

assign p_ZL4demo_0_0_ce0 = p_ZL4demo_0_0_ce0_local;

assign p_ZL4demo_0_1_address0 = zext_ln11_reg_505;

assign p_ZL4demo_0_1_ce0 = p_ZL4demo_0_1_ce0_local;

assign p_ZL4demo_0_2_address0 = zext_ln11_fu_329_p1;

assign p_ZL4demo_0_2_ce0 = p_ZL4demo_0_2_ce0_local;

assign p_ZL4demo_1_0_address0 = zext_ln11_reg_505;

assign p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;

assign p_ZL4demo_1_2_address0 = zext_ln11_fu_329_p1;

assign p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;

assign p_ZL4demo_2_0_address0 = zext_ln11_reg_505;

assign p_ZL4demo_2_0_ce0 = p_ZL4demo_2_0_ce0_local;

assign p_ZL4demo_2_1_address0 = zext_ln11_fu_329_p1;

assign p_ZL4demo_2_1_ce0 = p_ZL4demo_2_1_ce0_local;

assign p_ZL4demo_2_2_address0 = zext_ln11_reg_505_pp0_iter2_reg;

assign p_ZL4demo_2_2_ce0 = p_ZL4demo_2_2_ce0_local;

assign select_ln143_10_fu_386_p3 = ((icmp_ln145_reg_495_pp0_iter4_reg[0:0] == 1'b1) ? indvars_iv_next30_mid1_fu_381_p2 : indvars_iv_next3029_reg_500_pp0_iter4_reg);

assign select_ln143_9_fu_313_p3 = ((icmp_ln145_fu_293_p2[0:0] == 1'b1) ? indvars_iv_next3029_fu_307_p2 : ap_sig_allocacmp_i_load);

assign select_ln143_fu_299_p3 = ((icmp_ln145_fu_293_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign sext_ln124_1_cast_fu_253_p1 = $signed(sext_ln124_1);

assign sext_ln124_2_cast_fu_241_p1 = $signed(sext_ln124_2);

assign sext_ln124_3_cast_fu_237_p1 = $signed(sext_ln124_3);

assign sext_ln124_cast_fu_233_p1 = $signed(sext_ln124);

assign sub_ln15_fu_408_p2 = (add_ln15_14_fu_404_p2 - p_ZL4demo_2_2_load_reg_589);

assign tmp_21_fu_392_p3 = {{select_ln143_10_fu_386_p3}, {add_ln147_reg_529_pp0_iter4_reg}};

assign tmp_s_fu_321_p3 = {{select_ln143_9_fu_313_p3}, {select_ln143_fu_299_p3}};

assign zext_ln11_fu_329_p1 = tmp_s_fu_321_p3;

assign zext_ln124_1_cast_fu_249_p1 = zext_ln124_1;

assign zext_ln124_cast_fu_245_p1 = zext_ln124;

assign zext_ln147_fu_399_p1 = tmp_21_fu_392_p3;

always @ (posedge ap_clk) begin
    zext_ln124_cast_reg_471[7:2] <= 6'b000000;
    zext_ln124_1_cast_reg_476[7:2] <= 6'b000000;
    zext_ln11_reg_505[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln11_reg_505_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln11_reg_505_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //real_top_img_sharp_128_128_7_Pipeline_VITIS_LOOP_143_5_VITIS_LOOP_145_6
