// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_img_sharp_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        p_ZL4demo_0_0_address0,
        p_ZL4demo_0_0_ce0,
        p_ZL4demo_0_0_we0,
        p_ZL4demo_0_0_d0,
        p_ZL4demo_0_1_address0,
        p_ZL4demo_0_1_ce0,
        p_ZL4demo_0_1_we0,
        p_ZL4demo_0_1_d0,
        p_ZL4demo_0_2_address0,
        p_ZL4demo_0_2_ce0,
        p_ZL4demo_0_2_we0,
        p_ZL4demo_0_2_d0,
        p_ZL4demo_1_0_address0,
        p_ZL4demo_1_0_ce0,
        p_ZL4demo_1_0_we0,
        p_ZL4demo_1_0_d0,
        p_ZL4demo_1_1_address0,
        p_ZL4demo_1_1_ce0,
        p_ZL4demo_1_1_we0,
        p_ZL4demo_1_1_d0,
        p_ZL4demo_1_2_address0,
        p_ZL4demo_1_2_ce0,
        p_ZL4demo_1_2_we0,
        p_ZL4demo_1_2_d0,
        p_ZL4demo_2_0_address0,
        p_ZL4demo_2_0_ce0,
        p_ZL4demo_2_0_we0,
        p_ZL4demo_2_0_d0,
        p_ZL4demo_2_1_address0,
        p_ZL4demo_2_1_ce0,
        p_ZL4demo_2_1_we0,
        p_ZL4demo_2_1_d0,
        p_ZL4demo_2_2_address0,
        p_ZL4demo_2_2_ce0,
        p_ZL4demo_2_2_we0,
        p_ZL4demo_2_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [13:0] p_ZL4demo_0_0_address0;
output   p_ZL4demo_0_0_ce0;
output   p_ZL4demo_0_0_we0;
output  [7:0] p_ZL4demo_0_0_d0;
output  [13:0] p_ZL4demo_0_1_address0;
output   p_ZL4demo_0_1_ce0;
output   p_ZL4demo_0_1_we0;
output  [7:0] p_ZL4demo_0_1_d0;
output  [13:0] p_ZL4demo_0_2_address0;
output   p_ZL4demo_0_2_ce0;
output   p_ZL4demo_0_2_we0;
output  [7:0] p_ZL4demo_0_2_d0;
output  [13:0] p_ZL4demo_1_0_address0;
output   p_ZL4demo_1_0_ce0;
output   p_ZL4demo_1_0_we0;
output  [7:0] p_ZL4demo_1_0_d0;
output  [13:0] p_ZL4demo_1_1_address0;
output   p_ZL4demo_1_1_ce0;
output   p_ZL4demo_1_1_we0;
output  [7:0] p_ZL4demo_1_1_d0;
output  [13:0] p_ZL4demo_1_2_address0;
output   p_ZL4demo_1_2_ce0;
output   p_ZL4demo_1_2_we0;
output  [7:0] p_ZL4demo_1_2_d0;
output  [13:0] p_ZL4demo_2_0_address0;
output   p_ZL4demo_2_0_ce0;
output   p_ZL4demo_2_0_we0;
output  [7:0] p_ZL4demo_2_0_d0;
output  [13:0] p_ZL4demo_2_1_address0;
output   p_ZL4demo_2_1_ce0;
output   p_ZL4demo_2_1_we0;
output  [7:0] p_ZL4demo_2_1_d0;
output  [13:0] p_ZL4demo_2_2_address0;
output   p_ZL4demo_2_2_ce0;
output   p_ZL4demo_2_2_we0;
output  [7:0] p_ZL4demo_2_2_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln131_fu_288_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln131_reg_625;
wire   [0:0] icmp_ln132_fu_311_p2;
reg   [0:0] icmp_ln132_reg_629;
reg   [0:0] icmp_ln132_reg_629_pp0_iter2_reg;
wire   [0:0] xor_ln131_fu_317_p2;
reg   [0:0] xor_ln131_reg_637;
wire   [0:0] icmp_ln133_fu_323_p2;
reg   [0:0] icmp_ln133_reg_642;
wire   [0:0] and_ln131_2_fu_329_p2;
reg   [0:0] and_ln131_2_reg_647;
wire   [0:0] empty_fu_335_p2;
reg   [0:0] empty_reg_653;
wire   [5:0] select_ln132_fu_435_p3;
reg   [5:0] select_ln132_reg_658;
reg   [5:0] select_ln132_reg_658_pp0_iter3_reg;
wire   [1:0] y_mid2_fu_458_p3;
reg   [1:0] y_mid2_reg_664;
reg   [1:0] y_mid2_reg_664_pp0_iter3_reg;
wire   [1:0] select_ln133_fu_467_p3;
reg   [1:0] select_ln133_reg_669;
reg   [1:0] select_ln133_reg_669_pp0_iter3_reg;
wire   [5:0] select_ln131_3_fu_513_p3;
reg   [5:0] select_ln131_3_reg_674;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln135_fu_545_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_cast_fu_563_p1;
reg   [1:0] y_fu_76;
wire   [1:0] add_ln134_fu_483_p2;
wire    ap_loop_init;
reg   [1:0] x_fu_80;
reg   [3:0] indvar_flatten_fu_84;
wire   [3:0] select_ln133_2_fu_347_p3;
reg   [5:0] j_fu_88;
reg   [9:0] indvar_flatten12_fu_92;
wire   [9:0] select_ln132_2_fu_361_p3;
reg   [5:0] i_fu_96;
reg   [15:0] indvar_flatten35_fu_100;
wire   [15:0] add_ln131_2_fu_294_p2;
reg   [15:0] ap_sig_allocacmp_indvar_flatten35_load;
reg    A_ce0_local;
reg    p_ZL4demo_1_1_we0_local;
reg    p_ZL4demo_1_1_ce0_local;
reg    p_ZL4demo_1_0_we0_local;
reg    p_ZL4demo_1_0_ce0_local;
reg    p_ZL4demo_1_2_we0_local;
reg    p_ZL4demo_1_2_ce0_local;
reg    p_ZL4demo_0_1_we0_local;
reg    p_ZL4demo_0_1_ce0_local;
reg    p_ZL4demo_0_0_we0_local;
reg    p_ZL4demo_0_0_ce0_local;
reg    p_ZL4demo_0_2_we0_local;
reg    p_ZL4demo_0_2_ce0_local;
reg    p_ZL4demo_2_1_we0_local;
reg    p_ZL4demo_2_1_ce0_local;
reg    p_ZL4demo_2_0_we0_local;
reg    p_ZL4demo_2_0_ce0_local;
reg    p_ZL4demo_2_2_we0_local;
reg    p_ZL4demo_2_2_ce0_local;
wire   [3:0] add_ln133_2_fu_341_p2;
wire   [9:0] add_ln132_2_fu_355_p2;
wire   [5:0] select_ln131_fu_388_p3;
wire   [0:0] exitcond_flatten_not_fu_414_p2;
wire   [0:0] not_exitcond_flatten_mid234_fu_419_p2;
wire   [0:0] and_ln131_fu_424_p2;
wire   [0:0] icmp_ln134_fu_395_p2;
wire   [5:0] add_ln132_fu_401_p2;
wire   [1:0] x_mid26_fu_407_p3;
wire   [0:0] icmp_ln134_mid211_fu_429_p2;
wire   [0:0] empty_31_fu_448_p2;
wire   [0:0] empty_32_fu_453_p2;
wire   [1:0] add_ln133_fu_442_p2;
wire   [5:0] add_ln131_fu_507_p2;
wire   [5:0] zext_ln133_fu_520_p1;
wire   [5:0] zext_ln134_fu_529_p1;
wire   [5:0] empty_33_fu_523_p2;
wire   [5:0] add_ln135_fu_532_p2;
wire   [11:0] tmp_s_fu_537_p3;
wire   [12:0] tmp_fu_555_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 y_fu_76 = 2'd0;
#0 x_fu_80 = 2'd0;
#0 indvar_flatten_fu_84 = 4'd0;
#0 j_fu_88 = 6'd0;
#0 indvar_flatten12_fu_92 = 10'd0;
#0 i_fu_96 = 6'd0;
#0 indvar_flatten35_fu_100 = 16'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_96 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            i_fu_96 <= select_ln131_3_fu_513_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_92 <= 10'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln131_reg_625 == 1'd0))) begin
            indvar_flatten12_fu_92 <= select_ln132_2_fu_361_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln131_fu_288_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten35_fu_100 <= add_ln131_2_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_100 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_84 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln131_reg_625 == 1'd0))) begin
            indvar_flatten_fu_84 <= select_ln133_2_fu_347_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            j_fu_88 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j_fu_88 <= select_ln132_fu_435_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            x_fu_80 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            x_fu_80 <= select_ln133_fu_467_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            y_fu_76 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            y_fu_76 <= add_ln134_fu_483_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln131_2_reg_647 <= and_ln131_2_fu_329_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_653 <= empty_fu_335_p2;
        icmp_ln131_reg_625 <= icmp_ln131_fu_288_p2;
        icmp_ln132_reg_629 <= icmp_ln132_fu_311_p2;
        icmp_ln133_reg_642 <= icmp_ln133_fu_323_p2;
        xor_ln131_reg_637 <= xor_ln131_fu_317_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln132_reg_629_pp0_iter2_reg <= icmp_ln132_reg_629;
        select_ln131_3_reg_674 <= select_ln131_3_fu_513_p3;
        select_ln132_reg_658 <= select_ln132_fu_435_p3;
        select_ln132_reg_658_pp0_iter3_reg <= select_ln132_reg_658;
        select_ln133_reg_669 <= select_ln133_fu_467_p3;
        select_ln133_reg_669_pp0_iter3_reg <= select_ln133_reg_669;
        y_mid2_reg_664 <= y_mid2_fu_458_p3;
        y_mid2_reg_664_pp0_iter3_reg <= y_mid2_reg_664;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln131_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln131_reg_625 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten35_load = 16'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten35_load = indvar_flatten35_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd0) & (y_mid2_reg_664_pp0_iter3_reg == 2'd0))) begin
        p_ZL4demo_0_0_we0_local = 1'b1;
    end else begin
        p_ZL4demo_0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd0) & (y_mid2_reg_664_pp0_iter3_reg == 2'd1))) begin
        p_ZL4demo_0_1_we0_local = 1'b1;
    end else begin
        p_ZL4demo_0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(y_mid2_reg_664_pp0_iter3_reg == 2'd0) & ~(y_mid2_reg_664_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd0))) begin
        p_ZL4demo_0_2_we0_local = 1'b1;
    end else begin
        p_ZL4demo_0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd1) & (y_mid2_reg_664_pp0_iter3_reg == 2'd0))) begin
        p_ZL4demo_1_0_we0_local = 1'b1;
    end else begin
        p_ZL4demo_1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd1) & (y_mid2_reg_664_pp0_iter3_reg == 2'd1))) begin
        p_ZL4demo_1_1_we0_local = 1'b1;
    end else begin
        p_ZL4demo_1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(y_mid2_reg_664_pp0_iter3_reg == 2'd0) & ~(y_mid2_reg_664_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln133_reg_669_pp0_iter3_reg == 2'd1))) begin
        p_ZL4demo_1_2_we0_local = 1'b1;
    end else begin
        p_ZL4demo_1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_2_0_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln133_reg_669_pp0_iter3_reg == 2'd0) & ~(select_ln133_reg_669_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (y_mid2_reg_664_pp0_iter3_reg == 2'd0))) begin
        p_ZL4demo_2_0_we0_local = 1'b1;
    end else begin
        p_ZL4demo_2_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln133_reg_669_pp0_iter3_reg == 2'd0) & ~(select_ln133_reg_669_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (y_mid2_reg_664_pp0_iter3_reg == 2'd1))) begin
        p_ZL4demo_2_1_we0_local = 1'b1;
    end else begin
        p_ZL4demo_2_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_2_2_ce0_local = 1'b1;
    end else begin
        p_ZL4demo_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln133_reg_669_pp0_iter3_reg == 2'd0) & ~(y_mid2_reg_664_pp0_iter3_reg == 2'd0) & ~(y_mid2_reg_664_pp0_iter3_reg == 2'd1) & ~(select_ln133_reg_669_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL4demo_2_2_we0_local = 1'b1;
    end else begin
        p_ZL4demo_2_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln135_fu_545_p1;

assign A_ce0 = A_ce0_local;

assign add_ln131_2_fu_294_p2 = (ap_sig_allocacmp_indvar_flatten35_load + 16'd1);

assign add_ln131_fu_507_p2 = (i_fu_96 + 6'd1);

assign add_ln132_2_fu_355_p2 = (indvar_flatten12_fu_92 + 10'd1);

assign add_ln132_fu_401_p2 = (select_ln131_fu_388_p3 + 6'd1);

assign add_ln133_2_fu_341_p2 = (indvar_flatten_fu_84 + 4'd1);

assign add_ln133_fu_442_p2 = (x_mid26_fu_407_p3 + 2'd1);

assign add_ln134_fu_483_p2 = (y_mid2_fu_458_p3 + 2'd1);

assign add_ln135_fu_532_p2 = (zext_ln134_fu_529_p1 + select_ln132_reg_658);

assign and_ln131_2_fu_329_p2 = (xor_ln131_fu_317_p2 & icmp_ln133_fu_323_p2);

assign and_ln131_fu_424_p2 = (xor_ln131_reg_637 & not_exitcond_flatten_mid234_fu_419_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_31_fu_448_p2 = (icmp_ln134_mid211_fu_429_p2 | and_ln131_2_reg_647);

assign empty_32_fu_453_p2 = (icmp_ln132_reg_629 | empty_31_fu_448_p2);

assign empty_33_fu_523_p2 = (zext_ln133_fu_520_p1 + select_ln131_3_fu_513_p3);

assign empty_fu_335_p2 = (icmp_ln132_fu_311_p2 | and_ln131_2_fu_329_p2);

assign exitcond_flatten_not_fu_414_p2 = (icmp_ln133_reg_642 ^ 1'd1);

assign icmp_ln131_fu_288_p2 = ((ap_sig_allocacmp_indvar_flatten35_load == 16'd34596) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_311_p2 = ((indvar_flatten12_fu_92 == 10'd558) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_323_p2 = ((indvar_flatten_fu_84 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_395_p2 = ((y_fu_76 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln134_mid211_fu_429_p2 = (icmp_ln134_fu_395_p2 & and_ln131_fu_424_p2);

assign not_exitcond_flatten_mid234_fu_419_p2 = (icmp_ln132_reg_629 | exitcond_flatten_not_fu_414_p2);

assign p_ZL4demo_0_0_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_0_0_ce0 = p_ZL4demo_0_0_ce0_local;

assign p_ZL4demo_0_0_d0 = A_q0;

assign p_ZL4demo_0_0_we0 = p_ZL4demo_0_0_we0_local;

assign p_ZL4demo_0_1_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_0_1_ce0 = p_ZL4demo_0_1_ce0_local;

assign p_ZL4demo_0_1_d0 = A_q0;

assign p_ZL4demo_0_1_we0 = p_ZL4demo_0_1_we0_local;

assign p_ZL4demo_0_2_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_0_2_ce0 = p_ZL4demo_0_2_ce0_local;

assign p_ZL4demo_0_2_d0 = A_q0;

assign p_ZL4demo_0_2_we0 = p_ZL4demo_0_2_we0_local;

assign p_ZL4demo_1_0_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_1_0_ce0 = p_ZL4demo_1_0_ce0_local;

assign p_ZL4demo_1_0_d0 = A_q0;

assign p_ZL4demo_1_0_we0 = p_ZL4demo_1_0_we0_local;

assign p_ZL4demo_1_1_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_1_1_ce0 = p_ZL4demo_1_1_ce0_local;

assign p_ZL4demo_1_1_d0 = A_q0;

assign p_ZL4demo_1_1_we0 = p_ZL4demo_1_1_we0_local;

assign p_ZL4demo_1_2_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_1_2_ce0 = p_ZL4demo_1_2_ce0_local;

assign p_ZL4demo_1_2_d0 = A_q0;

assign p_ZL4demo_1_2_we0 = p_ZL4demo_1_2_we0_local;

assign p_ZL4demo_2_0_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_2_0_ce0 = p_ZL4demo_2_0_ce0_local;

assign p_ZL4demo_2_0_d0 = A_q0;

assign p_ZL4demo_2_0_we0 = p_ZL4demo_2_0_we0_local;

assign p_ZL4demo_2_1_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_2_1_ce0 = p_ZL4demo_2_1_ce0_local;

assign p_ZL4demo_2_1_d0 = A_q0;

assign p_ZL4demo_2_1_we0 = p_ZL4demo_2_1_we0_local;

assign p_ZL4demo_2_2_address0 = tmp_cast_fu_563_p1;

assign p_ZL4demo_2_2_ce0 = p_ZL4demo_2_2_ce0_local;

assign p_ZL4demo_2_2_d0 = A_q0;

assign p_ZL4demo_2_2_we0 = p_ZL4demo_2_2_we0_local;

assign select_ln131_3_fu_513_p3 = ((icmp_ln132_reg_629_pp0_iter2_reg[0:0] == 1'b1) ? add_ln131_fu_507_p2 : i_fu_96);

assign select_ln131_fu_388_p3 = ((icmp_ln132_reg_629[0:0] == 1'b1) ? 6'd0 : j_fu_88);

assign select_ln132_2_fu_361_p3 = ((icmp_ln132_fu_311_p2[0:0] == 1'b1) ? 10'd1 : add_ln132_2_fu_355_p2);

assign select_ln132_fu_435_p3 = ((and_ln131_2_reg_647[0:0] == 1'b1) ? add_ln132_fu_401_p2 : select_ln131_fu_388_p3);

assign select_ln133_2_fu_347_p3 = ((empty_fu_335_p2[0:0] == 1'b1) ? 4'd1 : add_ln133_2_fu_341_p2);

assign select_ln133_fu_467_p3 = ((icmp_ln134_mid211_fu_429_p2[0:0] == 1'b1) ? add_ln133_fu_442_p2 : x_mid26_fu_407_p3);

assign tmp_cast_fu_563_p1 = tmp_fu_555_p4;

assign tmp_fu_555_p4 = {{{select_ln131_3_reg_674}, {1'd0}}, {select_ln132_reg_658_pp0_iter3_reg}};

assign tmp_s_fu_537_p3 = {{empty_33_fu_523_p2}, {add_ln135_fu_532_p2}};

assign x_mid26_fu_407_p3 = ((empty_reg_653[0:0] == 1'b1) ? 2'd0 : x_fu_80);

assign xor_ln131_fu_317_p2 = (icmp_ln132_fu_311_p2 ^ 1'd1);

assign y_mid2_fu_458_p3 = ((empty_32_fu_453_p2[0:0] == 1'b1) ? 2'd0 : y_fu_76);

assign zext_ln133_fu_520_p1 = select_ln133_reg_669;

assign zext_ln134_fu_529_p1 = y_mid2_reg_664;

assign zext_ln135_fu_545_p1 = tmp_s_fu_537_p3;

endmodule //real_top_img_sharp_Pipeline_VITIS_LOOP_131_1_VITIS_LOOP_132_2_VITIS_LOOP_133_3_VITIS_LOOP
