// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_split_into_tiles_Pipeline_VITIS_LOOP_359_3_VITIS_LOOP_360_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tile1_address0,
        tile1_ce0,
        tile1_we0,
        tile1_d0,
        A_address0,
        A_ce0,
        A_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] tile1_address0;
output   tile1_ce0;
output   tile1_we0;
output  [7:0] tile1_d0;
output  [15:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln359_fu_111_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] add_ln362_fu_173_p2;
reg   [11:0] add_ln362_reg_263;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln362_1_fu_209_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln362_2_fu_235_p1;
reg   [6:0] j_fu_54;
wire   [6:0] add_ln360_fu_214_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_58;
wire   [6:0] select_ln359_1_fu_149_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [12:0] indvar_flatten6_fu_62;
wire   [12:0] add_ln359_1_fu_117_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    A_ce0_local;
reg    tile1_we0_local;
reg    tile1_ce0_local;
wire   [0:0] icmp_ln360_fu_135_p2;
wire   [6:0] add_ln359_fu_129_p2;
wire   [5:0] trunc_ln362_fu_157_p1;
wire   [6:0] select_ln359_fu_141_p3;
wire   [11:0] tmp_2_fu_161_p3;
wire   [11:0] zext_ln362_fu_169_p1;
wire   [0:0] bit_sel_fu_179_p3;
wire   [0:0] xor_ln362_fu_187_p2;
wire   [5:0] trunc_ln362_1_fu_193_p1;
wire   [14:0] tmp_3_fu_197_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_54 = 7'd0;
#0 i_fu_58 = 7'd0;
#0 indvar_flatten6_fu_62 = 13'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln359_fu_111_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_58 <= select_ln359_1_fu_149_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln359_fu_111_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_62 <= add_ln359_1_fu_117_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_62 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln359_fu_111_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_54 <= add_ln360_fu_214_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln362_reg_263 <= add_ln362_fu_173_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln359_fu_111_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_58;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tile1_ce0_local = 1'b1;
    end else begin
        tile1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tile1_we0_local = 1'b1;
    end else begin
        tile1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln362_1_fu_209_p1;

assign A_ce0 = A_ce0_local;

assign add_ln359_1_fu_117_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 13'd1);

assign add_ln359_fu_129_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln360_fu_214_p2 = (select_ln359_fu_141_p3 + 7'd1);

assign add_ln362_fu_173_p2 = (tmp_2_fu_161_p3 + zext_ln362_fu_169_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel_fu_179_p3 = select_ln359_fu_141_p3[7'd6];

assign icmp_ln359_fu_111_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln360_fu_135_p2 = ((ap_sig_allocacmp_j_load == 7'd64) ? 1'b1 : 1'b0);

assign select_ln359_1_fu_149_p3 = ((icmp_ln360_fu_135_p2[0:0] == 1'b1) ? add_ln359_fu_129_p2 : ap_sig_allocacmp_i_load);

assign select_ln359_fu_141_p3 = ((icmp_ln360_fu_135_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign tile1_address0 = zext_ln362_2_fu_235_p1;

assign tile1_ce0 = tile1_ce0_local;

assign tile1_d0 = A_q0;

assign tile1_we0 = tile1_we0_local;

assign tmp_2_fu_161_p3 = {{trunc_ln362_fu_157_p1}, {6'd0}};

assign tmp_3_fu_197_p5 = {{{{select_ln359_1_fu_149_p3}, {1'd0}}, {xor_ln362_fu_187_p2}}, {trunc_ln362_1_fu_193_p1}};

assign trunc_ln362_1_fu_193_p1 = select_ln359_fu_141_p3[5:0];

assign trunc_ln362_fu_157_p1 = select_ln359_1_fu_149_p3[5:0];

assign xor_ln362_fu_187_p2 = (bit_sel_fu_179_p3 ^ 1'd1);

assign zext_ln362_1_fu_209_p1 = tmp_3_fu_197_p5;

assign zext_ln362_2_fu_235_p1 = add_ln362_reg_263;

assign zext_ln362_fu_169_p1 = select_ln359_fu_141_p3;

endmodule //real_top_split_into_tiles_Pipeline_VITIS_LOOP_359_3_VITIS_LOOP_360_4
