// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_split_into_tiles_Pipeline_VITIS_LOOP_368_5_VITIS_LOOP_369_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        tile2_address0,
        tile2_ce0,
        tile2_we0,
        tile2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [13:0] tile2_address0;
output   tile2_ce0;
output   tile2_we0;
output  [7:0] tile2_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln368_fu_109_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] add_ln371_fu_205_p2;
reg   [13:0] add_ln371_reg_261;
wire   [63:0] zext_ln371_1_fu_200_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln371_2_fu_227_p1;
reg   [7:0] j_fu_52;
wire   [7:0] add_ln369_fu_211_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_56;
wire   [7:0] select_ln368_1_fu_152_p3;
reg   [14:0] indvar_flatten13_fu_60;
wire   [14:0] add_ln368_1_fu_115_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    A_ce0_local;
reg    tile2_we0_local;
reg    tile2_ce0_local;
wire   [0:0] icmp_ln369_fu_138_p2;
wire   [7:0] add_ln368_fu_132_p2;
wire   [6:0] trunc_ln371_fu_160_p1;
wire   [0:0] bit_sel1_fu_172_p3;
wire   [7:0] select_ln368_fu_144_p3;
wire   [0:0] xor_val2_fu_180_p2;
wire   [15:0] tmp_5_fu_190_p4;
wire   [13:0] tmp_4_fu_164_p3;
wire   [13:0] zext_ln371_fu_186_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_52 = 8'd0;
#0 i_fu_56 = 8'd0;
#0 indvar_flatten13_fu_60 = 15'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_56 <= select_ln368_1_fu_152_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln368_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_60 <= add_ln368_1_fu_115_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_60 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_52 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_52 <= add_ln369_fu_211_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln371_reg_261 <= add_ln371_fu_205_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln368_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile2_ce0_local = 1'b1;
    end else begin
        tile2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile2_we0_local = 1'b1;
    end else begin
        tile2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln371_1_fu_200_p1;

assign A_ce0 = A_ce0_local;

assign add_ln368_1_fu_115_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 15'd1);

assign add_ln368_fu_132_p2 = (i_fu_56 + 8'd1);

assign add_ln369_fu_211_p2 = (select_ln368_fu_144_p3 + 8'd1);

assign add_ln371_fu_205_p2 = (tmp_4_fu_164_p3 + zext_ln371_fu_186_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel1_fu_172_p3 = select_ln368_1_fu_152_p3[8'd7];

assign icmp_ln368_fu_109_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln369_fu_138_p2 = ((j_fu_52 == 8'd128) ? 1'b1 : 1'b0);

assign select_ln368_1_fu_152_p3 = ((icmp_ln369_fu_138_p2[0:0] == 1'b1) ? add_ln368_fu_132_p2 : i_fu_56);

assign select_ln368_fu_144_p3 = ((icmp_ln369_fu_138_p2[0:0] == 1'b1) ? 8'd0 : j_fu_52);

assign tile2_address0 = zext_ln371_2_fu_227_p1;

assign tile2_ce0 = tile2_ce0_local;

assign tile2_d0 = A_q0;

assign tile2_we0 = tile2_we0_local;

assign tmp_4_fu_164_p3 = {{trunc_ln371_fu_160_p1}, {7'd0}};

assign tmp_5_fu_190_p4 = {{{xor_val2_fu_180_p2}, {trunc_ln371_fu_160_p1}}, {select_ln368_fu_144_p3}};

assign trunc_ln371_fu_160_p1 = select_ln368_1_fu_152_p3[6:0];

assign xor_val2_fu_180_p2 = (bit_sel1_fu_172_p3 ^ 1'd1);

assign zext_ln371_1_fu_200_p1 = tmp_5_fu_190_p4;

assign zext_ln371_2_fu_227_p1 = add_ln371_reg_261;

assign zext_ln371_fu_186_p1 = select_ln368_fu_144_p3;

endmodule //real_top_split_into_tiles_Pipeline_VITIS_LOOP_368_5_VITIS_LOOP_369_6
