// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_convol_Pipeline_VITIS_LOOP_286_11_VITIS_LOOP_287_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inter_6_address0,
        inter_6_ce0,
        inter_6_q0,
        inter_6_address1,
        inter_6_ce1,
        inter_6_q1,
        inter_6_address2,
        inter_6_ce2,
        inter_6_q2,
        inter_6_address3,
        inter_6_ce3,
        inter_6_q3,
        inter_7_address0,
        inter_7_ce0,
        inter_7_we0,
        inter_7_d0,
        max_ret7_max_fu_283_p_din1,
        max_ret7_max_fu_283_p_din2,
        max_ret7_max_fu_283_p_din3,
        max_ret7_max_fu_283_p_din4,
        max_ret7_max_fu_283_p_dout0,
        max_ret7_max_fu_283_p_ready
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] inter_6_address0;
output   inter_6_ce0;
input  [7:0] inter_6_q0;
output  [7:0] inter_6_address1;
output   inter_6_ce1;
input  [7:0] inter_6_q1;
output  [7:0] inter_6_address2;
output   inter_6_ce2;
input  [7:0] inter_6_q2;
output  [7:0] inter_6_address3;
output   inter_6_ce3;
input  [7:0] inter_6_q3;
output  [5:0] inter_7_address0;
output   inter_7_ce0;
output   inter_7_we0;
output  [7:0] inter_7_d0;
output  [7:0] max_ret7_max_fu_283_p_din1;
output  [7:0] max_ret7_max_fu_283_p_din2;
output  [7:0] max_ret7_max_fu_283_p_din3;
output  [7:0] max_ret7_max_fu_283_p_din4;
input  [7:0] max_ret7_max_fu_283_p_dout0;
input   max_ret7_max_fu_283_p_ready;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln286_fu_161_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] tmp_s_fu_221_p4;
reg   [2:0] tmp_s_reg_358;
reg   [2:0] tmp_s_reg_358_pp0_iter1_reg;
wire   [2:0] tmp_20_fu_259_p4;
reg   [2:0] tmp_20_reg_373;
reg   [2:0] tmp_20_reg_373_pp0_iter1_reg;
reg   [7:0] inter_6_load_reg_388;
reg   [7:0] inter_6_load_1_reg_393;
reg   [7:0] inter_6_load_2_reg_398;
reg   [7:0] inter_6_load_3_reg_403;
wire    ap_block_pp0_stage0_ignoreCallOp58;
wire   [63:0] zext_ln288_fu_239_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln288_1_fu_254_p1;
wire   [63:0] zext_ln288_2_fu_279_p1;
wire   [63:0] zext_ln288_3_fu_296_p1;
wire   [63:0] zext_ln288_4_fu_328_p1;
reg   [4:0] j_fu_60;
wire   [4:0] add_ln287_fu_301_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_64;
wire   [4:0] select_ln286_1_fu_209_p3;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [6:0] indvar_flatten13_fu_68;
wire   [6:0] add_ln286_1_fu_167_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    inter_6_ce3_local;
reg    inter_6_ce2_local;
reg    inter_6_ce1_local;
reg    inter_6_ce0_local;
reg    inter_7_we0_local;
reg    inter_7_ce0_local;
wire   [0:0] tmp_fu_189_p3;
wire   [3:0] trunc_ln286_fu_179_p1;
wire   [3:0] select_ln286_fu_197_p3;
wire   [4:0] add_ln286_fu_183_p2;
wire   [3:0] trunc_ln288_fu_217_p1;
wire   [7:0] add_ln_fu_231_p3;
wire   [7:0] add_ln288_1_fu_244_p4;
wire   [7:0] tmp_21_fu_269_p4;
wire   [7:0] tmp_22_fu_284_p5;
wire   [4:0] zext_ln286_fu_205_p1;
wire   [5:0] tmp_23_fu_322_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_60 = 5'd0;
#0 i_fu_64 = 5'd0;
#0 indvar_flatten13_fu_68 = 7'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln286_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= select_ln286_1_fu_209_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln286_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_68 <= add_ln286_1_fu_167_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_68 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln286_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_60 <= add_ln287_fu_301_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_60 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_20_reg_373 <= {{select_ln286_fu_197_p3[3:1]}};
        tmp_20_reg_373_pp0_iter1_reg <= tmp_20_reg_373;
        tmp_s_reg_358 <= {{select_ln286_1_fu_209_p3[3:1]}};
        tmp_s_reg_358_pp0_iter1_reg <= tmp_s_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_6_load_1_reg_393 <= inter_6_q2;
        inter_6_load_2_reg_398 <= inter_6_q1;
        inter_6_load_3_reg_403 <= inter_6_q0;
        inter_6_load_reg_388 <= inter_6_q3;
    end
end

always @ (*) begin
    if (((icmp_ln286_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_6_ce0_local = 1'b1;
    end else begin
        inter_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_6_ce1_local = 1'b1;
    end else begin
        inter_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_6_ce2_local = 1'b1;
    end else begin
        inter_6_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_6_ce3_local = 1'b1;
    end else begin
        inter_6_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inter_7_ce0_local = 1'b1;
    end else begin
        inter_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inter_7_we0_local = 1'b1;
    end else begin
        inter_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln286_1_fu_167_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 7'd1);

assign add_ln286_fu_183_p2 = (ap_sig_allocacmp_i_load + 5'd2);

assign add_ln287_fu_301_p2 = (zext_ln286_fu_205_p1 + 5'd2);

assign add_ln288_1_fu_244_p4 = {{{tmp_s_fu_221_p4}, {1'd1}}, {select_ln286_fu_197_p3}};

assign add_ln_fu_231_p3 = {{trunc_ln288_fu_217_p1}, {select_ln286_fu_197_p3}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp58 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln286_fu_161_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 7'd64) ? 1'b1 : 1'b0);

assign inter_6_address0 = zext_ln288_3_fu_296_p1;

assign inter_6_address1 = zext_ln288_1_fu_254_p1;

assign inter_6_address2 = zext_ln288_2_fu_279_p1;

assign inter_6_address3 = zext_ln288_fu_239_p1;

assign inter_6_ce0 = inter_6_ce0_local;

assign inter_6_ce1 = inter_6_ce1_local;

assign inter_6_ce2 = inter_6_ce2_local;

assign inter_6_ce3 = inter_6_ce3_local;

assign inter_7_address0 = zext_ln288_4_fu_328_p1;

assign inter_7_ce0 = inter_7_ce0_local;

assign inter_7_d0 = max_ret7_max_fu_283_p_dout0;

assign inter_7_we0 = inter_7_we0_local;

assign max_ret7_max_fu_283_p_din1 = inter_6_load_reg_388;

assign max_ret7_max_fu_283_p_din2 = inter_6_load_1_reg_393;

assign max_ret7_max_fu_283_p_din3 = inter_6_load_2_reg_398;

assign max_ret7_max_fu_283_p_din4 = inter_6_load_3_reg_403;

assign select_ln286_1_fu_209_p3 = ((tmp_fu_189_p3[0:0] == 1'b1) ? add_ln286_fu_183_p2 : ap_sig_allocacmp_i_load);

assign select_ln286_fu_197_p3 = ((tmp_fu_189_p3[0:0] == 1'b1) ? 4'd0 : trunc_ln286_fu_179_p1);

assign tmp_20_fu_259_p4 = {{select_ln286_fu_197_p3[3:1]}};

assign tmp_21_fu_269_p4 = {{{trunc_ln288_fu_217_p1}, {tmp_20_fu_259_p4}}, {1'd1}};

assign tmp_22_fu_284_p5 = {{{{tmp_s_fu_221_p4}, {1'd1}}, {tmp_20_fu_259_p4}}, {1'd1}};

assign tmp_23_fu_322_p3 = {{tmp_s_reg_358_pp0_iter1_reg}, {tmp_20_reg_373_pp0_iter1_reg}};

assign tmp_fu_189_p3 = ap_sig_allocacmp_j_load[32'd4];

assign tmp_s_fu_221_p4 = {{select_ln286_1_fu_209_p3[3:1]}};

assign trunc_ln286_fu_179_p1 = ap_sig_allocacmp_j_load[3:0];

assign trunc_ln288_fu_217_p1 = select_ln286_1_fu_209_p3[3:0];

assign zext_ln286_fu_205_p1 = select_ln286_fu_197_p3;

assign zext_ln288_1_fu_254_p1 = add_ln288_1_fu_244_p4;

assign zext_ln288_2_fu_279_p1 = tmp_21_fu_269_p4;

assign zext_ln288_3_fu_296_p1 = tmp_22_fu_284_p5;

assign zext_ln288_4_fu_328_p1 = tmp_23_fu_322_p3;

assign zext_ln288_fu_239_p1 = add_ln_fu_231_p3;

endmodule //real_top_convol_Pipeline_VITIS_LOOP_286_11_VITIS_LOOP_287_12
