// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="real_top_real_top,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7s75-fgga676-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.946000,HLS_SYN_LAT=1580525,HLS_SYN_TPT=none,HLS_SYN_MEM=136,HLS_SYN_DSP=0,HLS_SYN_FF=7208,HLS_SYN_LUT=19310,HLS_VERSION=2025_1}" *)

module real_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        out_r_address1,
        out_r_ce1,
        out_r_we1,
        out_r_d1
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_pp0_stage0 = 13'd1024;
parameter    ap_ST_fsm_pp0_stage1 = 13'd2048;
parameter    ap_ST_fsm_state14 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [7:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [7:0] out_r_address1;
output   out_r_ce1;
output   out_r_we1;
output  [7:0] out_r_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] icmp_ln4007_reg_253;
wire   [3:0] select_ln399_fu_413_p3;
reg   [3:0] select_ln399_reg_602;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_fu_421_p3;
reg   [3:0] i_reg_609;
wire   [2:0] trunc_ln403_fu_429_p1;
reg   [2:0] trunc_ln403_reg_615;
reg   [0:0] bit_sel1_reg_621;
reg   [0:0] bit_sel_reg_646;
wire   [2:0] trunc_ln405_fu_475_p1;
reg   [2:0] trunc_ln405_reg_651;
wire   [0:0] xor_ln405_fu_498_p2;
reg   [0:0] xor_ln405_reg_657;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [7:0] out2_load_reg_662;
reg   [7:0] out3_load_reg_667;
wire   [0:0] icmp_ln400_fu_527_p2;
reg   [0:0] icmp_ln400_reg_672;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln399_fu_533_p2;
reg   [0:0] icmp_ln399_reg_677;
wire    ap_CS_fsm_state10;
wire    grp_convol_fu_264_ap_done;
wire    ap_block_pp0_stage1_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg   [13:0] tile0_address0;
reg    tile0_ce0;
reg    tile0_we0;
wire   [7:0] tile0_q0;
reg   [13:0] tile1_address0;
reg    tile1_ce0;
reg    tile1_we0;
wire   [7:0] tile1_q0;
reg   [13:0] tile2_address0;
reg    tile2_ce0;
reg    tile2_we0;
wire   [7:0] tile2_q0;
reg   [13:0] tile3_address0;
reg    tile3_ce0;
reg    tile3_we0;
wire   [7:0] tile3_q0;
reg   [5:0] out0_address0;
reg    out0_ce0;
reg    out0_we0;
wire   [7:0] out0_q0;
reg    out0_ce1;
reg    out0_we1;
reg   [5:0] out1_address0;
reg    out1_ce0;
reg    out1_we0;
wire   [7:0] out1_q0;
reg    out1_ce1;
reg    out1_we1;
reg   [5:0] out2_address0;
reg    out2_ce0;
reg    out2_we0;
wire   [7:0] out2_q0;
reg    out2_ce1;
reg    out2_we1;
reg   [5:0] out3_address0;
reg    out3_ce0;
reg    out3_we0;
wire   [7:0] out3_q0;
reg    out3_ce1;
reg    out3_we1;
wire    grp_convol_fu_264_ap_start;
wire    grp_convol_fu_264_ap_idle;
wire    grp_convol_fu_264_ap_ready;
wire   [13:0] grp_convol_fu_264_A_address0;
wire    grp_convol_fu_264_A_ce0;
reg   [7:0] grp_convol_fu_264_A_q0;
wire   [5:0] grp_convol_fu_264_out_r_address0;
wire    grp_convol_fu_264_out_r_ce0;
wire    grp_convol_fu_264_out_r_we0;
wire   [7:0] grp_convol_fu_264_out_r_d0;
wire   [5:0] grp_convol_fu_264_out_r_address1;
wire    grp_convol_fu_264_out_r_ce1;
wire    grp_convol_fu_264_out_r_we1;
wire   [7:0] grp_convol_fu_264_out_r_d1;
wire    grp_split_into_tiles_fu_372_ap_start;
wire    grp_split_into_tiles_fu_372_ap_done;
wire    grp_split_into_tiles_fu_372_ap_idle;
wire    grp_split_into_tiles_fu_372_ap_ready;
wire   [15:0] grp_split_into_tiles_fu_372_A_address0;
wire    grp_split_into_tiles_fu_372_A_ce0;
wire   [13:0] grp_split_into_tiles_fu_372_tile0_address0;
wire    grp_split_into_tiles_fu_372_tile0_ce0;
wire    grp_split_into_tiles_fu_372_tile0_we0;
wire   [7:0] grp_split_into_tiles_fu_372_tile0_d0;
wire   [13:0] grp_split_into_tiles_fu_372_tile1_address0;
wire    grp_split_into_tiles_fu_372_tile1_ce0;
wire    grp_split_into_tiles_fu_372_tile1_we0;
wire   [7:0] grp_split_into_tiles_fu_372_tile1_d0;
wire   [13:0] grp_split_into_tiles_fu_372_tile2_address0;
wire    grp_split_into_tiles_fu_372_tile2_ce0;
wire    grp_split_into_tiles_fu_372_tile2_we0;
wire   [7:0] grp_split_into_tiles_fu_372_tile2_d0;
wire   [13:0] grp_split_into_tiles_fu_372_tile3_address0;
wire    grp_split_into_tiles_fu_372_tile3_ce0;
wire    grp_split_into_tiles_fu_372_tile3_we0;
wire   [7:0] grp_split_into_tiles_fu_372_tile3_d0;
reg   [0:0] ap_phi_mux_icmp_ln4007_phi_fu_257_p4;
wire    ap_block_pp0_stage0;
reg    grp_convol_fu_264_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
reg    grp_split_into_tiles_fu_372_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln403_2_fu_459_p1;
wire   [63:0] zext_ln403_1_fu_493_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln405_fu_511_p1;
wire   [63:0] zext_ln407_fu_562_p1;
wire   [63:0] zext_ln409_fu_576_p1;
reg   [5:0] indvar_flatten4_fu_118;
wire   [5:0] add_ln399_1_fu_521_p2;
reg   [3:0] i5_fu_122;
reg   [3:0] j6_fu_126;
wire   [3:0] j_fu_516_p2;
reg    out0_ce0_local;
reg    out1_ce0_local;
reg    out2_ce0_local;
reg    out3_ce0_local;
reg    out_r_we1_local;
reg   [7:0] out_r_d1_local;
reg    out_r_ce1_local;
reg   [7:0] out_r_address1_local;
reg    out_r_we0_local;
reg   [7:0] out_r_d0_local;
reg    out_r_ce0_local;
reg   [7:0] out_r_address0_local;
wire   [3:0] add_ln399_fu_407_p2;
wire   [5:0] tmp_fu_433_p3;
wire   [5:0] zext_ln403_fu_449_p1;
wire   [5:0] add_ln403_fu_453_p2;
wire   [7:0] tmp_8_fu_487_p3;
wire   [7:0] tmp_s_fu_503_p4;
wire   [0:0] xor_val2_fu_549_p2;
wire   [7:0] tmp_9_fu_554_p4;
wire   [7:0] tmp_1_fu_567_p5;
wire    ap_CS_fsm_state14;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_convol_fu_264_ap_start_reg = 1'b0;
#0 grp_split_into_tiles_fu_372_ap_start_reg = 1'b0;
#0 indvar_flatten4_fu_118 = 6'd0;
#0 i5_fu_122 = 4'd0;
#0 j6_fu_126 = 4'd0;
end

real_top_tile0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tile0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tile0_address0),
    .ce0(tile0_ce0),
    .we0(tile0_we0),
    .d0(grp_split_into_tiles_fu_372_tile0_d0),
    .q0(tile0_q0)
);

real_top_tile0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tile1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tile1_address0),
    .ce0(tile1_ce0),
    .we0(tile1_we0),
    .d0(grp_split_into_tiles_fu_372_tile1_d0),
    .q0(tile1_q0)
);

real_top_tile0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tile2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tile2_address0),
    .ce0(tile2_ce0),
    .we0(tile2_we0),
    .d0(grp_split_into_tiles_fu_372_tile2_d0),
    .q0(tile2_q0)
);

real_top_tile0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tile3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tile3_address0),
    .ce0(tile3_ce0),
    .we0(tile3_we0),
    .d0(grp_split_into_tiles_fu_372_tile3_d0),
    .q0(tile3_q0)
);

real_top_out0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
out0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out0_address0),
    .ce0(out0_ce0),
    .we0(out0_we0),
    .d0(grp_convol_fu_264_out_r_d0),
    .q0(out0_q0),
    .address1(grp_convol_fu_264_out_r_address1),
    .ce1(out0_ce1),
    .we1(out0_we1),
    .d1(grp_convol_fu_264_out_r_d1)
);

real_top_out0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
out1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out1_address0),
    .ce0(out1_ce0),
    .we0(out1_we0),
    .d0(grp_convol_fu_264_out_r_d0),
    .q0(out1_q0),
    .address1(grp_convol_fu_264_out_r_address1),
    .ce1(out1_ce1),
    .we1(out1_we1),
    .d1(grp_convol_fu_264_out_r_d1)
);

real_top_out0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
out2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out2_address0),
    .ce0(out2_ce0),
    .we0(out2_we0),
    .d0(grp_convol_fu_264_out_r_d0),
    .q0(out2_q0),
    .address1(grp_convol_fu_264_out_r_address1),
    .ce1(out2_ce1),
    .we1(out2_we1),
    .d1(grp_convol_fu_264_out_r_d1)
);

real_top_out0_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
out3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out3_address0),
    .ce0(out3_ce0),
    .we0(out3_we0),
    .d0(grp_convol_fu_264_out_r_d0),
    .q0(out3_q0),
    .address1(grp_convol_fu_264_out_r_address1),
    .ce1(out3_ce1),
    .we1(out3_we1),
    .d1(grp_convol_fu_264_out_r_d1)
);

real_top_convol grp_convol_fu_264(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_convol_fu_264_ap_start),
    .ap_done(grp_convol_fu_264_ap_done),
    .ap_idle(grp_convol_fu_264_ap_idle),
    .ap_ready(grp_convol_fu_264_ap_ready),
    .A_address0(grp_convol_fu_264_A_address0),
    .A_ce0(grp_convol_fu_264_A_ce0),
    .A_q0(grp_convol_fu_264_A_q0),
    .out_r_address0(grp_convol_fu_264_out_r_address0),
    .out_r_ce0(grp_convol_fu_264_out_r_ce0),
    .out_r_we0(grp_convol_fu_264_out_r_we0),
    .out_r_d0(grp_convol_fu_264_out_r_d0),
    .out_r_address1(grp_convol_fu_264_out_r_address1),
    .out_r_ce1(grp_convol_fu_264_out_r_ce1),
    .out_r_we1(grp_convol_fu_264_out_r_we1),
    .out_r_d1(grp_convol_fu_264_out_r_d1)
);

real_top_split_into_tiles grp_split_into_tiles_fu_372(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_split_into_tiles_fu_372_ap_start),
    .ap_done(grp_split_into_tiles_fu_372_ap_done),
    .ap_idle(grp_split_into_tiles_fu_372_ap_idle),
    .ap_ready(grp_split_into_tiles_fu_372_ap_ready),
    .A_address0(grp_split_into_tiles_fu_372_A_address0),
    .A_ce0(grp_split_into_tiles_fu_372_A_ce0),
    .A_q0(A_q0),
    .tile0_address0(grp_split_into_tiles_fu_372_tile0_address0),
    .tile0_ce0(grp_split_into_tiles_fu_372_tile0_ce0),
    .tile0_we0(grp_split_into_tiles_fu_372_tile0_we0),
    .tile0_d0(grp_split_into_tiles_fu_372_tile0_d0),
    .tile1_address0(grp_split_into_tiles_fu_372_tile1_address0),
    .tile1_ce0(grp_split_into_tiles_fu_372_tile1_ce0),
    .tile1_we0(grp_split_into_tiles_fu_372_tile1_we0),
    .tile1_d0(grp_split_into_tiles_fu_372_tile1_d0),
    .tile2_address0(grp_split_into_tiles_fu_372_tile2_address0),
    .tile2_ce0(grp_split_into_tiles_fu_372_tile2_ce0),
    .tile2_we0(grp_split_into_tiles_fu_372_tile2_we0),
    .tile2_d0(grp_split_into_tiles_fu_372_tile2_d0),
    .tile3_address0(grp_split_into_tiles_fu_372_tile3_address0),
    .tile3_ce0(grp_split_into_tiles_fu_372_tile3_ce0),
    .tile3_we0(grp_split_into_tiles_fu_372_tile3_we0),
    .tile3_d0(grp_split_into_tiles_fu_372_tile3_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state10) & (grp_convol_fu_264_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state10) & (grp_convol_fu_264_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state10) & (grp_convol_fu_264_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_convol_fu_264_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_convol_fu_264_ap_start_reg <= 1'b1;
        end else if ((grp_convol_fu_264_ap_ready == 1'b1)) begin
            grp_convol_fu_264_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_split_into_tiles_fu_372_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_split_into_tiles_fu_372_ap_start_reg <= 1'b1;
        end else if ((grp_split_into_tiles_fu_372_ap_ready == 1'b1)) begin
            grp_split_into_tiles_fu_372_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i5_fu_122 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i5_fu_122 <= i_fu_421_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln399_reg_677 == 1'd0))) begin
        icmp_ln4007_reg_253 <= icmp_ln400_reg_672;
    end else if (((1'b1 == ap_CS_fsm_state10) & (grp_convol_fu_264_ap_done == 1'b1))) begin
        icmp_ln4007_reg_253 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten4_fu_118 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        indvar_flatten4_fu_118 <= add_ln399_1_fu_521_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j6_fu_126 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        j6_fu_126 <= j_fu_516_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bit_sel1_reg_621 <= i_fu_421_p3[4'd3];
        bit_sel_reg_646 <= select_ln399_fu_413_p3[4'd3];
        i_reg_609 <= i_fu_421_p3;
        select_ln399_reg_602 <= select_ln399_fu_413_p3;
        trunc_ln403_reg_615 <= trunc_ln403_fu_429_p1;
        trunc_ln405_reg_651 <= trunc_ln405_fu_475_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln399_reg_677 <= icmp_ln399_fu_533_p2;
        out2_load_reg_662 <= out2_q0;
        out3_load_reg_667 <= out3_q0;
        xor_ln405_reg_657 <= xor_ln405_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        icmp_ln400_reg_672 <= icmp_ln400_fu_527_p2;
    end
end

always @ (*) begin
    if ((grp_convol_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_split_into_tiles_fu_372_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_convol_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_convol_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_convol_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln399_fu_533_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln399_reg_677 == 1'd0))) begin
        ap_phi_mux_icmp_ln4007_phi_fu_257_p4 = icmp_ln400_reg_672;
    end else begin
        ap_phi_mux_icmp_ln4007_phi_fu_257_p4 = icmp_ln4007_reg_253;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_convol_fu_264_A_q0 = tile3_q0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_convol_fu_264_A_q0 = tile2_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_convol_fu_264_A_q0 = tile1_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_convol_fu_264_A_q0 = tile0_q0;
    end else begin
        grp_convol_fu_264_A_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out0_address0 = grp_convol_fu_264_out_r_address0;
    end else begin
        out0_address0 = zext_ln403_2_fu_459_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out0_ce0 = grp_convol_fu_264_out_r_ce0;
    end else begin
        out0_ce0 = out0_ce0_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out0_ce0_local = 1'b1;
    end else begin
        out0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out0_ce1 = grp_convol_fu_264_out_r_ce1;
    end else begin
        out0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out0_we0 = grp_convol_fu_264_out_r_we0;
    end else begin
        out0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out0_we1 = grp_convol_fu_264_out_r_we1;
    end else begin
        out0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out1_address0 = grp_convol_fu_264_out_r_address0;
    end else begin
        out1_address0 = zext_ln403_2_fu_459_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out1_ce0 = grp_convol_fu_264_out_r_ce0;
    end else begin
        out1_ce0 = out1_ce0_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out1_ce0_local = 1'b1;
    end else begin
        out1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out1_ce1 = grp_convol_fu_264_out_r_ce1;
    end else begin
        out1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out1_we0 = grp_convol_fu_264_out_r_we0;
    end else begin
        out1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out1_we1 = grp_convol_fu_264_out_r_we1;
    end else begin
        out1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out2_address0 = grp_convol_fu_264_out_r_address0;
    end else begin
        out2_address0 = zext_ln403_2_fu_459_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out2_ce0 = grp_convol_fu_264_out_r_ce0;
    end else begin
        out2_ce0 = out2_ce0_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out2_ce0_local = 1'b1;
    end else begin
        out2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out2_ce1 = grp_convol_fu_264_out_r_ce1;
    end else begin
        out2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out2_we0 = grp_convol_fu_264_out_r_we0;
    end else begin
        out2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out2_we1 = grp_convol_fu_264_out_r_we1;
    end else begin
        out2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out3_address0 = grp_convol_fu_264_out_r_address0;
    end else begin
        out3_address0 = zext_ln403_2_fu_459_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out3_ce0 = grp_convol_fu_264_out_r_ce0;
    end else begin
        out3_ce0 = out3_ce0_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out3_ce0_local = 1'b1;
    end else begin
        out3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out3_ce1 = grp_convol_fu_264_out_r_ce1;
    end else begin
        out3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out3_we0 = grp_convol_fu_264_out_r_we0;
    end else begin
        out3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out3_we1 = grp_convol_fu_264_out_r_we1;
    end else begin
        out3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        out_r_address0_local = zext_ln409_fu_576_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        out_r_address0_local = zext_ln405_fu_511_p1;
    end else begin
        out_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        out_r_address1_local = zext_ln407_fu_562_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        out_r_address1_local = zext_ln403_1_fu_493_p1;
    end else begin
        out_r_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        out_r_ce1_local = 1'b1;
    end else begin
        out_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        out_r_d0_local = out3_load_reg_667;
    end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        out_r_d0_local = out1_q0;
    end else begin
        out_r_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        out_r_d1_local = out2_load_reg_662;
    end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        out_r_d1_local = out0_q0;
    end else begin
        out_r_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        out_r_we1_local = 1'b1;
    end else begin
        out_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile0_address0 = grp_split_into_tiles_fu_372_tile0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tile0_address0 = grp_convol_fu_264_A_address0;
    end else begin
        tile0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile0_ce0 = grp_split_into_tiles_fu_372_tile0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tile0_ce0 = grp_convol_fu_264_A_ce0;
    end else begin
        tile0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile0_we0 = grp_split_into_tiles_fu_372_tile0_we0;
    end else begin
        tile0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile1_address0 = grp_split_into_tiles_fu_372_tile1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tile1_address0 = grp_convol_fu_264_A_address0;
    end else begin
        tile1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile1_ce0 = grp_split_into_tiles_fu_372_tile1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tile1_ce0 = grp_convol_fu_264_A_ce0;
    end else begin
        tile1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile1_we0 = grp_split_into_tiles_fu_372_tile1_we0;
    end else begin
        tile1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile2_address0 = grp_split_into_tiles_fu_372_tile2_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tile2_address0 = grp_convol_fu_264_A_address0;
    end else begin
        tile2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile2_ce0 = grp_split_into_tiles_fu_372_tile2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tile2_ce0 = grp_convol_fu_264_A_ce0;
    end else begin
        tile2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile2_we0 = grp_split_into_tiles_fu_372_tile2_we0;
    end else begin
        tile2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile3_address0 = grp_split_into_tiles_fu_372_tile3_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tile3_address0 = grp_convol_fu_264_A_address0;
    end else begin
        tile3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile3_ce0 = grp_split_into_tiles_fu_372_tile3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tile3_ce0 = grp_convol_fu_264_A_ce0;
    end else begin
        tile3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile3_we0 = grp_split_into_tiles_fu_372_tile3_we0;
    end else begin
        tile3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_split_into_tiles_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_convol_fu_264_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_convol_fu_264_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_convol_fu_264_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_convol_fu_264_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_split_into_tiles_fu_372_A_address0;

assign A_ce0 = grp_split_into_tiles_fu_372_A_ce0;

assign add_ln399_1_fu_521_p2 = (indvar_flatten4_fu_118 + 6'd1);

assign add_ln399_fu_407_p2 = (i5_fu_122 + 4'd1);

assign add_ln403_fu_453_p2 = (tmp_fu_433_p3 + zext_ln403_fu_449_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_convol_fu_264_ap_start = grp_convol_fu_264_ap_start_reg;

assign grp_split_into_tiles_fu_372_ap_start = grp_split_into_tiles_fu_372_ap_start_reg;

assign i_fu_421_p3 = ((ap_phi_mux_icmp_ln4007_phi_fu_257_p4[0:0] == 1'b1) ? add_ln399_fu_407_p2 : i5_fu_122);

assign icmp_ln399_fu_533_p2 = ((indvar_flatten4_fu_118 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln400_fu_527_p2 = ((j_fu_516_p2 == 4'd8) ? 1'b1 : 1'b0);

assign j_fu_516_p2 = (select_ln399_reg_602 + 4'd1);

assign out_r_address0 = out_r_address0_local;

assign out_r_address1 = out_r_address1_local;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_ce1 = out_r_ce1_local;

assign out_r_d0 = out_r_d0_local;

assign out_r_d1 = out_r_d1_local;

assign out_r_we0 = out_r_we0_local;

assign out_r_we1 = out_r_we1_local;

assign select_ln399_fu_413_p3 = ((ap_phi_mux_icmp_ln4007_phi_fu_257_p4[0:0] == 1'b1) ? 4'd0 : j6_fu_126);

assign tmp_1_fu_567_p5 = {{{{xor_val2_fu_549_p2}, {trunc_ln403_reg_615}}, {xor_ln405_reg_657}}, {trunc_ln405_reg_651}};

assign tmp_8_fu_487_p3 = {{i_reg_609}, {select_ln399_reg_602}};

assign tmp_9_fu_554_p4 = {{{xor_val2_fu_549_p2}, {trunc_ln403_reg_615}}, {select_ln399_reg_602}};

assign tmp_fu_433_p3 = {{trunc_ln403_fu_429_p1}, {3'd0}};

assign tmp_s_fu_503_p4 = {{{i_reg_609}, {xor_ln405_fu_498_p2}}, {trunc_ln405_reg_651}};

assign trunc_ln403_fu_429_p1 = i_fu_421_p3[2:0];

assign trunc_ln405_fu_475_p1 = select_ln399_fu_413_p3[2:0];

assign xor_ln405_fu_498_p2 = (bit_sel_reg_646 ^ 1'd1);

assign xor_val2_fu_549_p2 = (bit_sel1_reg_621 ^ 1'd1);

assign zext_ln403_1_fu_493_p1 = tmp_8_fu_487_p3;

assign zext_ln403_2_fu_459_p1 = add_ln403_fu_453_p2;

assign zext_ln403_fu_449_p1 = select_ln399_fu_413_p3;

assign zext_ln405_fu_511_p1 = tmp_s_fu_503_p4;

assign zext_ln407_fu_562_p1 = tmp_9_fu_554_p4;

assign zext_ln409_fu_576_p1 = tmp_1_fu_567_p5;

endmodule //real_top
