// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module real_top_convol_Pipeline_VITIS_LOOP_308_15_VITIS_LOOP_309_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inter_8_address0,
        inter_8_ce0,
        inter_8_q0,
        inter_8_address1,
        inter_8_ce1,
        inter_8_q1,
        inter_8_address2,
        inter_8_ce2,
        inter_8_q2,
        inter_8_address3,
        inter_8_ce3,
        inter_8_q3,
        inter_9_address0,
        inter_9_ce0,
        inter_9_we0,
        inter_9_d0,
        max_ret7_max_fu_283_p_din1,
        max_ret7_max_fu_283_p_din2,
        max_ret7_max_fu_283_p_din3,
        max_ret7_max_fu_283_p_din4,
        max_ret7_max_fu_283_p_dout0,
        max_ret7_max_fu_283_p_ready
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] inter_8_address0;
output   inter_8_ce0;
input  [7:0] inter_8_q0;
output  [5:0] inter_8_address1;
output   inter_8_ce1;
input  [7:0] inter_8_q1;
output  [5:0] inter_8_address2;
output   inter_8_ce2;
input  [7:0] inter_8_q2;
output  [5:0] inter_8_address3;
output   inter_8_ce3;
input  [7:0] inter_8_q3;
output  [3:0] inter_9_address0;
output   inter_9_ce0;
output   inter_9_we0;
output  [7:0] inter_9_d0;
output  [7:0] max_ret7_max_fu_283_p_din1;
output  [7:0] max_ret7_max_fu_283_p_din2;
output  [7:0] max_ret7_max_fu_283_p_din3;
output  [7:0] max_ret7_max_fu_283_p_din4;
input  [7:0] max_ret7_max_fu_283_p_dout0;
input   max_ret7_max_fu_283_p_ready;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln308_fu_164_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] tmp_s_fu_224_p4;
reg   [1:0] tmp_s_reg_361;
reg   [1:0] tmp_s_reg_361_pp0_iter1_reg;
wire   [1:0] tmp_16_fu_262_p4;
reg   [1:0] tmp_16_reg_376;
reg   [1:0] tmp_16_reg_376_pp0_iter1_reg;
reg   [7:0] max_ret4_reg_391;
wire    ap_block_pp0_stage0_11001_ignoreCallOp52;
wire    ap_block_pp0_stage0_ignoreCallOp52;
wire   [63:0] zext_ln310_fu_242_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln310_1_fu_257_p1;
wire   [63:0] zext_ln310_2_fu_282_p1;
wire   [63:0] zext_ln310_3_fu_299_p1;
wire   [63:0] zext_ln310_4_fu_331_p1;
reg   [3:0] j_fu_60;
wire   [3:0] add_ln309_fu_304_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_64;
wire   [3:0] select_ln308_1_fu_212_p3;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [4:0] indvar_flatten20_fu_68;
wire   [4:0] add_ln308_1_fu_170_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten20_load;
reg    inter_8_ce3_local;
reg    inter_8_ce2_local;
reg    inter_8_ce1_local;
reg    inter_8_ce0_local;
reg    inter_9_we0_local;
reg    inter_9_ce0_local;
wire   [0:0] tmp_fu_192_p3;
wire   [2:0] trunc_ln308_fu_182_p1;
wire   [2:0] select_ln308_fu_200_p3;
wire   [3:0] add_ln308_fu_186_p2;
wire   [2:0] trunc_ln310_fu_220_p1;
wire   [5:0] add_ln_fu_234_p3;
wire   [5:0] add_ln310_1_fu_247_p4;
wire   [5:0] tmp_17_fu_272_p4;
wire   [5:0] tmp_18_fu_287_p5;
wire   [3:0] zext_ln308_fu_208_p1;
wire   [3:0] tmp_19_fu_325_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_60 = 4'd0;
#0 i_fu_64 = 4'd0;
#0 indvar_flatten20_fu_68 = 5'd0;
#0 ap_done_reg = 1'b0;
end

real_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln308_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= select_ln308_1_fu_212_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln308_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_68 <= add_ln308_1_fu_170_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_68 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln308_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_60 <= add_ln309_fu_304_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_60 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_16_reg_376 <= {{select_ln308_fu_200_p3[2:1]}};
        tmp_16_reg_376_pp0_iter1_reg <= tmp_16_reg_376;
        tmp_s_reg_361 <= {{select_ln308_1_fu_212_p3[2:1]}};
        tmp_s_reg_361_pp0_iter1_reg <= tmp_s_reg_361;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp52) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_ret4_reg_391 <= max_ret7_max_fu_283_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln308_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_8_ce0_local = 1'b1;
    end else begin
        inter_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_8_ce1_local = 1'b1;
    end else begin
        inter_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_8_ce2_local = 1'b1;
    end else begin
        inter_8_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_8_ce3_local = 1'b1;
    end else begin
        inter_8_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inter_9_ce0_local = 1'b1;
    end else begin
        inter_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inter_9_we0_local = 1'b1;
    end else begin
        inter_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln308_1_fu_170_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 5'd1);

assign add_ln308_fu_186_p2 = (ap_sig_allocacmp_i_load + 4'd2);

assign add_ln309_fu_304_p2 = (zext_ln308_fu_208_p1 + 4'd2);

assign add_ln310_1_fu_247_p4 = {{{tmp_s_fu_224_p4}, {1'd1}}, {select_ln308_fu_200_p3}};

assign add_ln_fu_234_p3 = {{trunc_ln310_fu_220_p1}, {select_ln308_fu_200_p3}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp52 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp52 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln308_fu_164_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 5'd16) ? 1'b1 : 1'b0);

assign inter_8_address0 = zext_ln310_3_fu_299_p1;

assign inter_8_address1 = zext_ln310_1_fu_257_p1;

assign inter_8_address2 = zext_ln310_2_fu_282_p1;

assign inter_8_address3 = zext_ln310_fu_242_p1;

assign inter_8_ce0 = inter_8_ce0_local;

assign inter_8_ce1 = inter_8_ce1_local;

assign inter_8_ce2 = inter_8_ce2_local;

assign inter_8_ce3 = inter_8_ce3_local;

assign inter_9_address0 = zext_ln310_4_fu_331_p1;

assign inter_9_ce0 = inter_9_ce0_local;

assign inter_9_d0 = max_ret4_reg_391;

assign inter_9_we0 = inter_9_we0_local;

assign max_ret7_max_fu_283_p_din1 = inter_8_q3;

assign max_ret7_max_fu_283_p_din2 = inter_8_q2;

assign max_ret7_max_fu_283_p_din3 = inter_8_q1;

assign max_ret7_max_fu_283_p_din4 = inter_8_q0;

assign select_ln308_1_fu_212_p3 = ((tmp_fu_192_p3[0:0] == 1'b1) ? add_ln308_fu_186_p2 : ap_sig_allocacmp_i_load);

assign select_ln308_fu_200_p3 = ((tmp_fu_192_p3[0:0] == 1'b1) ? 3'd0 : trunc_ln308_fu_182_p1);

assign tmp_16_fu_262_p4 = {{select_ln308_fu_200_p3[2:1]}};

assign tmp_17_fu_272_p4 = {{{trunc_ln310_fu_220_p1}, {tmp_16_fu_262_p4}}, {1'd1}};

assign tmp_18_fu_287_p5 = {{{{tmp_s_fu_224_p4}, {1'd1}}, {tmp_16_fu_262_p4}}, {1'd1}};

assign tmp_19_fu_325_p3 = {{tmp_s_reg_361_pp0_iter1_reg}, {tmp_16_reg_376_pp0_iter1_reg}};

assign tmp_fu_192_p3 = ap_sig_allocacmp_j_load[32'd3];

assign tmp_s_fu_224_p4 = {{select_ln308_1_fu_212_p3[2:1]}};

assign trunc_ln308_fu_182_p1 = ap_sig_allocacmp_j_load[2:0];

assign trunc_ln310_fu_220_p1 = select_ln308_1_fu_212_p3[2:0];

assign zext_ln308_fu_208_p1 = select_ln308_fu_200_p3;

assign zext_ln310_1_fu_257_p1 = add_ln310_1_fu_247_p4;

assign zext_ln310_2_fu_282_p1 = tmp_17_fu_272_p4;

assign zext_ln310_3_fu_299_p1 = tmp_18_fu_287_p5;

assign zext_ln310_4_fu_331_p1 = tmp_19_fu_325_p3;

assign zext_ln310_fu_242_p1 = add_ln_fu_234_p3;

endmodule //real_top_convol_Pipeline_VITIS_LOOP_308_15_VITIS_LOOP_309_16
